---@meta _

AP_BOTTOM = 8          -- object/Avi
AP_BOTTOMLEFT = 2      -- object/Avi
AP_BOTTOMRIGHT = 3     -- object/Avi
AP_CENTER = 4          -- object/Avi
AP_LEFT = 6            -- object/Avi
AP_RIGHT = 7           -- object/Avi
AP_TOP = 5             -- object/Avi
AP_TOPLEFT = 0         -- object/Avi
AP_TOPRIGHT = 1        -- object/Avi
CT_ABILITY = 2         -- object/Avi
CT_EXPEDITION_NAME = 3 -- object/Avi
CT_NAME = 1            -- object/Avi
DC_ALWAYS = 0          -- object/Avi
DC_SHIFT_KEY_DOWN = 1  -- object/Avi

---object/Avi
---@enum AVI_PATH
local AVI_PATH = {
  ALL_01_RECRUIT        = "objects/machinima/avi/all_01_recruit.avi",
  ALL_02_MEMORY         = "objects/machinima/avi/all_02_memory.avi",
  ALL_04_SON            = "objects/machinima/avi/all_04_son.avi",
  ALL_15_PLATEAU        = "objects/machinima/avi/all_15_plateau.avi",
  ALL_16_RIVER          = "objects/machinima/avi/all_16_river.avi",
  ALL_17_POST           = "objects/machinima/avi/all_17_post.avi",
  ALL_19_INVADE         = "objects/machinima/avi/all_19_invade.avi",
  ALL_20_POLLUTE        = "objects/machinima/avi/all_20_pollute.avi",
  ALL_21_PURIFY_C12     = "objects/machinima/avi/all_21_purify_c12.avi",
  ALL_21_PURIFY_C43     = "objects/machinima/avi/all_21_purify_c43.avi",
  ALL_23_SANDGLASS_01   = "objects/machinima/avi/all_23_sandglass_01.avi",
  ALL_23_SANDGLASS_02   = "objects/machinima/avi/all_23_sandglass_02.avi",
  ALL_24_GATE           = "objects/machinima/avi/all_24_gate.avi",
  ALL_29_ARRIVAL        = "objects/machinima/avi/all_29_arrival.avi",
  ALL_35_DEATH01        = "objects/machinima/avi/all_35_death01.avi",
  ALL_41_ABBYS          = "objects/machinima/avi/all_41_abbys.avi",
  ALL_42_ALTAR          = "objects/machinima/avi/all_42_altar.avi",
  BLACK                 = "objects/machinima/avi/black.avi",
  CI                    = "objects/machinima/avi/ci.avi",
  DW_03_GOLEM_AVI       = "objects/machinima/avi/dw_03_golem_avi.avi",
  ETC_01_ANTHALON       = "objects/machinima/avi/etc_01_anthalon.avi",
  ETC_02_KRAKEN         = "objects/machinima/avi/etc_02_kraken.avi",
  ETC_03_REVI           = "objects/machinima/avi/etc_03_revi.avi",
  ETC_04_KRAKEN         = "objects/machinima/avi/etc_04_kraken.avi",
  ETC_05_LEVI           = "objects/machinima/avi/etc_05_levi.avi",
  ETC_06_LIBRARY_1      = "objects/machinima/avi/etc_06_library_1.avi",
  ETC_06_LIBRARY_2      = "objects/machinima/avi/etc_06_library_2.avi",
  ETC_06_LIBRARY_3      = "objects/machinima/avi/etc_06_library_3.avi",
  ETC_06_LIBRARY_4      = "objects/machinima/avi/etc_06_library_4.avi",
  ETC_07_FEAST_00       = "objects/machinima/avi/etc_07_feast_00.avi",
  ETC_07_FEAST_01       = "objects/machinima/avi/etc_07_feast_01.avi",
  ETC_07_FEAST_02       = "objects/machinima/avi/etc_07_feast_02.avi",
  ETC_07_FEAST_03       = "objects/machinima/avi/etc_07_feast_03.avi",
  ETC_07_FEAST_04       = "objects/machinima/avi/etc_07_feast_04.avi",
  ETC_09_HEIR           = "objects/machinima/avi/etc_09_heir.avi",
  ETC_10_NUIA           = "objects/machinima/avi/etc_10_nuia.avi",
  ETC_10_NUIA_SOUND     = "objects/machinima/avi/etc_10_nuia_sound.avi",
  ETC_11_HARIHARA       = "objects/machinima/avi/etc_11_harihara.avi",
  ETC_11_HARIHARA_SOUND = "objects/machinima/avi/etc_11_harihara_sound.avi",
  ETC_12_PIRATE         = "objects/machinima/avi/etc_12_pirate.avi",
  ETC_12_PIRATE_SOUND   = "objects/machinima/avi/etc_12_pirate_sound.avi",
  ETC_14_KADUM          = "objects/machinima/avi/etc_14_kadum.avi",
  ETC_15_SURVIVOR       = "objects/machinima/avi/etc_15_survivor.avi",
  ID_300_01             = "objects/machinima/avi/id_300_01.avi",
  ID_300_06_DW          = "objects/machinima/avi/id_300_06_dw.avi",
  ID_300_06_EL          = "objects/machinima/avi/id_300_06_el.avi",
  ID_300_06_FE          = "objects/machinima/avi/id_300_06_fe.avi",
  ID_300_06_HA          = "objects/machinima/avi/id_300_06_ha.avi",
  ID_300_06_NU          = "objects/machinima/avi/id_300_06_nu.avi",
  OP_EL                 = "objects/machinima/avi/op_el.avi",
  OP_FE                 = "objects/machinima/avi/op_fe.avi",
  OP_HA                 = "objects/machinima/avi/op_ha.avi",
  OP_NU                 = "objects/machinima/avi/op_nu.avi",
  OP_START              = "objects/machinima/avi/op_start.avi",
  SL_ALL_01             = "objects/machinima/avi/sl_all_01.avi",
  SL_ALL_02             = "objects/machinima/avi/sl_all_02.avi",
  SL_ALL_03             = "objects/machinima/avi/sl_all_03.avi",
  SL_ALL_04             = "objects/machinima/avi/sl_all_04.avi",
  SL_ALL_05             = "objects/machinima/avi/sl_all_05.avi",
  SL_ALL_06             = "objects/machinima/avi/sl_all_06.avi",
  SL_ALL_07             = "objects/machinima/avi/sl_all_07.avi",
  SL_ALL_07_WA          = "objects/machinima/avi/sl_all_07_wa.avi",
  SL_ALL_08             = "objects/machinima/avi/sl_all_08.avi",
  SL_ALL_09             = "objects/machinima/avi/sl_all_09.avi",
  SL_ALL_10             = "objects/machinima/avi/sl_all_10.avi",
  SL_ALL_11             = "objects/machinima/avi/sl_all_11.avi",
  SL_ALL_12             = "objects/machinima/avi/sl_all_12.avi",
  SL_ALL_13             = "objects/machinima/avi/sl_all_13.avi",
  SL_ALL_14             = "objects/machinima/avi/sl_all_14.avi",
  SL_ALL_15             = "objects/machinima/avi/sl_all_15.avi",
  SL_ALL_16             = "objects/machinima/avi/sl_all_16.avi",
  SL_DW_001             = "objects/machinima/avi/sl_dw_001.avi",
  SL_DW_002             = "objects/machinima/avi/sl_dw_002.avi",
  SL_DW_003             = "objects/machinima/avi/sl_dw_003.avi",
  SL_DW_004             = "objects/machinima/avi/sl_dw_004.avi",
  SL_DW_005             = "objects/machinima/avi/sl_dw_005.avi",
  SL_DW_006             = "objects/machinima/avi/sl_dw_006.avi",
  SL_DW_007             = "objects/machinima/avi/sl_dw_007.avi",
  SL_DW_008             = "objects/machinima/avi/sl_dw_008.avi",
  SL_EL_001             = "objects/machinima/avi/sl_el_001.avi",
  SL_EL_002             = "objects/machinima/avi/sl_el_002.avi",
  SL_EL_003             = "objects/machinima/avi/sl_el_003.avi",
  SL_EL_004             = "objects/machinima/avi/sl_el_004.avi",
  SL_EL_005             = "objects/machinima/avi/sl_el_005.avi",
  SL_EL_007             = "objects/machinima/avi/sl_el_007.avi",
  SL_EL_008             = "objects/machinima/avi/sl_el_008.avi",
  SL_EL_009             = "objects/machinima/avi/sl_el_009.avi",
  SL_EL_010             = "objects/machinima/avi/sl_el_010.avi",
  SL_EL_011             = "objects/machinima/avi/sl_el_011.avi",
  SL_EL_012             = "objects/machinima/avi/sl_el_012.avi",
  SL_EL_013             = "objects/machinima/avi/sl_el_013.avi",
  SL_EL_014             = "objects/machinima/avi/sl_el_014.avi",
  SL_EL_015             = "objects/machinima/avi/sl_el_015.avi",
  SL_EL_016             = "objects/machinima/avi/sl_el_016.avi",
  SL_EL_017             = "objects/machinima/avi/sl_el_017.avi",
  SL_EL_018             = "objects/machinima/avi/sl_el_018.avi",
  SL_EL_019             = "objects/machinima/avi/sl_el_019.avi",
  SL_EL_021             = "objects/machinima/avi/sl_el_021.avi",
  SL_EL_022             = "objects/machinima/avi/sl_el_022.avi",
  SL_EL_023             = "objects/machinima/avi/sl_el_023.avi",
  SL_EL_024             = "objects/machinima/avi/sl_el_024.avi",
  SL_EL_028             = "objects/machinima/avi/sl_el_028.avi",
  SL_FE_001             = "objects/machinima/avi/sl_fe_001.avi",
  SL_FE_002             = "objects/machinima/avi/sl_fe_002.avi",
  SL_FE_003             = "objects/machinima/avi/sl_fe_003.avi",
  SL_FE_004             = "objects/machinima/avi/sl_fe_004.avi",
  SL_FE_005             = "objects/machinima/avi/sl_fe_005.avi",
  SL_FE_006             = "objects/machinima/avi/sl_fe_006.avi",
  SL_FE_007             = "objects/machinima/avi/sl_fe_007.avi",
  SL_FE_008             = "objects/machinima/avi/sl_fe_008.avi",
  SL_FE_009             = "objects/machinima/avi/sl_fe_009.avi",
  SL_FE_010             = "objects/machinima/avi/sl_fe_010.avi",
  SL_FE_011             = "objects/machinima/avi/sl_fe_011.avi",
  SL_FE_012             = "objects/machinima/avi/sl_fe_012.avi",
  SL_FE_013             = "objects/machinima/avi/sl_fe_013.avi",
  SL_FE_014             = "objects/machinima/avi/sl_fe_014.avi",
  SL_FE_015             = "objects/machinima/avi/sl_fe_015.avi",
  SL_FE_016             = "objects/machinima/avi/sl_fe_016.avi",
  SL_FE_017             = "objects/machinima/avi/sl_fe_017.avi",
  SL_FE_018             = "objects/machinima/avi/sl_fe_018.avi",
  SL_FE_019             = "objects/machinima/avi/sl_fe_019.avi",
  SL_FE_020             = "objects/machinima/avi/sl_fe_020.avi",
  SL_FE_021             = "objects/machinima/avi/sl_fe_021.avi",
  SL_FE_022             = "objects/machinima/avi/sl_fe_022.avi",
  SL_FE_023             = "objects/machinima/avi/sl_fe_023.avi",
  SL_FE_024             = "objects/machinima/avi/sl_fe_024.avi",
  SL_FE_028             = "objects/machinima/avi/sl_fe_028.avi",
  SL_FE_029             = "objects/machinima/avi/sl_fe_029.avi",
  SL_HA_001             = "objects/machinima/avi/sl_ha_001.avi",
  SL_HA_002             = "objects/machinima/avi/sl_ha_002.avi",
  SL_HA_003             = "objects/machinima/avi/sl_ha_003.avi",
  SL_HA_004             = "objects/machinima/avi/sl_ha_004.avi",
  SL_HA_005             = "objects/machinima/avi/sl_ha_005.avi",
  SL_HA_006             = "objects/machinima/avi/sl_ha_006.avi",
  SL_HA_007             = "objects/machinima/avi/sl_ha_007.avi",
  SL_HA_009             = "objects/machinima/avi/sl_ha_009.avi",
  SL_HA_010             = "objects/machinima/avi/sl_ha_010.avi",
  SL_HA_011             = "objects/machinima/avi/sl_ha_011.avi",
  SL_HA_012             = "objects/machinima/avi/sl_ha_012.avi",
  SL_HA_013             = "objects/machinima/avi/sl_ha_013.avi",
  SL_HA_014             = "objects/machinima/avi/sl_ha_014.avi",
  SL_HA_015             = "objects/machinima/avi/sl_ha_015.avi",
  SL_HA_016             = "objects/machinima/avi/sl_ha_016.avi",
  SL_HA_017             = "objects/machinima/avi/sl_ha_017.avi",
  SL_HA_018             = "objects/machinima/avi/sl_ha_018.avi",
  SL_HA_019             = "objects/machinima/avi/sl_ha_019.avi",
  SL_HA_020             = "objects/machinima/avi/sl_ha_020.avi",
  SL_HA_022             = "objects/machinima/avi/sl_ha_022.avi",
  SL_HA_023             = "objects/machinima/avi/sl_ha_023.avi",
  SL_HA_024             = "objects/machinima/avi/sl_ha_024.avi",
  SL_HA_028             = "objects/machinima/avi/sl_ha_028.avi",
  SL_HA_029             = "objects/machinima/avi/sl_ha_029.avi",
  SL_NU_001             = "objects/machinima/avi/sl_nu_001.avi",
  SL_NU_002             = "objects/machinima/avi/sl_nu_002.avi",
  SL_NU_004             = "objects/machinima/avi/sl_nu_004.avi",
  SL_NU_005             = "objects/machinima/avi/sl_nu_005.avi",
  SL_NU_006             = "objects/machinima/avi/sl_nu_006.avi",
  SL_NU_007             = "objects/machinima/avi/sl_nu_007.avi",
  SL_NU_008             = "objects/machinima/avi/sl_nu_008.avi",
  SL_NU_010             = "objects/machinima/avi/sl_nu_010.avi",
  SL_NU_011             = "objects/machinima/avi/sl_nu_011.avi",
  SL_NU_012             = "objects/machinima/avi/sl_nu_012.avi",
  SL_NU_013             = "objects/machinima/avi/sl_nu_013.avi",
  SL_NU_014             = "objects/machinima/avi/sl_nu_014.avi",
  SL_NU_015             = "objects/machinima/avi/sl_nu_015.avi",
  SL_NU_016             = "objects/machinima/avi/sl_nu_016.avi",
  SL_NU_017             = "objects/machinima/avi/sl_nu_017.avi",
  SL_NU_018             = "objects/machinima/avi/sl_nu_018.avi",
  SL_NU_019             = "objects/machinima/avi/sl_nu_019.avi",
  SL_NU_020             = "objects/machinima/avi/sl_nu_020.avi",
  SL_NU_021             = "objects/machinima/avi/sl_nu_021.avi",
  SL_NU_024             = "objects/machinima/avi/sl_nu_024.avi",
  SL_WB_001             = "objects/machinima/avi/sl_wb_001.avi",
  SL_WB_002             = "objects/machinima/avi/sl_wb_002.avi",
  SL_WB_003             = "objects/machinima/avi/sl_wb_003.avi",
  SL_WB_004             = "objects/machinima/avi/sl_wb_004.avi",
  SL_WB_005             = "objects/machinima/avi/sl_wb_005.avi",
  SL_WB_006             = "objects/machinima/avi/sl_wb_006.avi",
  SL_WB_007             = "objects/machinima/avi/sl_wb_007.avi",
  SL_WB_008             = "objects/machinima/avi/sl_wb_008.avi",
  WB_06_FAIL            = "objects/machinima/avi/wb_06_fail.avi",
  WB_07_DREAM           = "objects/machinima/avi/wb_07_dream.avi",
  WB_08_PRAY            = "objects/machinima/avi/wb_08_pray.avi",
}

---object/Avi
---@class Avi: Widget
---@class avi: Avi
local Avi = {}

---Sets the AVI file to be used by the widget.
---@param fileName AVI_PATH The path to the AVI file.
---@usage
---```
---widget:SetAviName("objects/machinima/avi/ci.avi")
---```
function Avi:SetAviName(fileName) end

---@TODO: Not sure what avitype is as any value doesnt cause an error.
---@param depth number
---@param aviType? any
function Avi:SetAviNum(depth, aviType) end
