---@class GearScoreItemInfo
---@field total number
---@field equipSlotReinforce number
---@field bare number

---@class SocketInfo
---@field maxSocket number
---@field socketItem number[]

---@class EvolvingInfoModifier
---@field value number
---@field type number
---@field gsNum number

---@class EvolvingInfo
---@field minExp number
---@field evolveChance number
---@field minSectionExp number
---@field percent number
---@field modifier EvolvingInfoModifier[]

---@class ModifireTable
---@field value number
---@field type number
---@field name string

---@class BonusesInfo
---@field bufDesc string
---@field satisfied boolean
---@field numPieces number

---@class EquipSetInfo
---@field equipSetItemInfoDesc string
---@field bonuses BonusesInfo[]

---@class SetItemsInfo
---@field item_name string
---@field equipped boolean
---@field item_type number

---@class RechargeBuffInfo
---@field chargeLifetime Time
---@field remainTime Time

---@class RequiredConditionInfo
---@field equipSlotTypes string[]

---This may not be complete
---@class ItemInfo
---@field useAsSkin boolean
---@field description string
---@field cost number
---@field soul_bind string
---@field level number
---@field isMaterial boolean
---@field level_limit number
---@field itemType number
---@field gender string
---@field grade string
---@field sideEffect boolean
---@field isEnchantDisable boolean
---@field lookChanged boolean
---@field name string
---@field securityState number
---@field maxStack number
---@field contributionPointPrice number
---@field convertibleItem boolean
---@field dead boolean
---@field needsUnpack boolean
---@field isUnderWaterCreature boolean
---@field indestructible boolean
---@field craftedWorldName string
---@field isMyWorld boolean
---@field crafter string
---@field itemUsage string
---@field icon string
---@field soul_bind_type number
---@field soul_bound number
---@field locked boolean
---@field livingPointPrice number
---@field stack number
---@field processedState string
---@field craftType number
---@field gradeIcon string
---@field auction_only boolean
---@field gradeEnchantable boolean
---@field level_requirement number
---@field itemGrade number
---@field isPetOnly boolean
---@field lookType number
---@field useConsumeItem boolean
---@field honorPrice number
---@field skillType number
---@field category string
---@field refund number
---@field item_flag_cannot_equip boolean
---@field item_impl string
---@field gradeColor string
---@field isStackable boolean
---@field sellable boolean
---@field maxDurability number
---@field maxDamage number
---@field slotTypeNum number
---@field repairable number
---@field armorType string
---@field equiped boolean
---@field scalable boolean
---@field buffType number
---@field element string
---@field durability number
---@field armor number
---@field magicResistance number
---@field extraArmor number
---@field useAsStat boolean
---@field slotType string
---@field overIcon string
---@field lifeSpan number
---@field lifeSpanType string
---@field lifeSpanDayOfWeek boolean
---@field backpackType number
---@field moveSpeed number
---@field location_zone_name string
---@field location_world_name string
---@field gearScore GearScoreItemInfo
---@field checkUnitReq boolean
---@field uccTooltip string
---@field socketInfo SocketInfo
---@field gemInfo number
---@field magicDps number
---@field minDamage number
---@field baseEquipment boolean
---@field elementName string
---@field healDps number
---@field attackDelay number
---@field DPS number
---@field extraDPS number
---@field evolvingInfo EvolvingInfo
---@field evolvingCategory boolean
---@field canEvolve boolean
---@field gemModifireTable ModifireTable[]
---@field modifier ModifireTable[]
---@field equipSetInfo EquipSetInfo
---@field wear boolean
---@field maxSetItemCount number
---@field equippedSetItemCount number
---@field setItems SetItemsInfo[]
---@field rechargeBuff RechargeBuffInfo
---@field requiredCondition RequiredConditionInfo

---UICategory id.
---@alias UIC
---| `UIC_ABILITY_CHANGE`
---| `UIC_ACHIEVEMENT`
---| `UIC_ACTABILITY`
---| `UIC_ADDON`
---| `UIC_APPELLATION`
---| `UIC_AUCTION`
---| `UIC_AUTH_MSG_WND`
---| `UIC_BAG`
---| `UIC_BANK`
---| `UIC_BEAUTY_SHOP`
---| `UIC_BLESS_UTHSTIN`
---| `UIC_BUTLER_INFO`
---| `UIC_CHALLENGE`
---| `UIC_CHANGE_VISUAL_RACE`
---| `UIC_CHARACTER_INFO`
---| `UIC_CHARACTER_INFO_VISUAL_RACE`
---| `UIC_CHECK_BOT_WND`
---| `UIC_CHECK_SECOND_PASSWORD`
---| `UIC_CHRONICLE_BOOK_WND`
---| `UIC_CLEAR_SECOND_PASSWORD`
---| `UIC_CLIENT_DIRVEN_CONTENTS`
---| `UIC_CLIENT_DIRVEN_TITLE`
---| `UIC_CLIENT_DRIVEN_EXIT_BTN`
---| `UIC_COFFER`
---| `UIC_COMMERCIAL_MAIL`
---| `UIC_COMMUNITY`
---| `UIC_CRAFT_BOOK`
---| `UIC_CRAFT_ORDER`
---| `UIC_CREATE_EXPEDITION`
---| `UIC_DEATH_AND_RESURRECTION_WND`
---| `UIC_DEV_WINDOW`
---| `UIC_DROPDOWN_LIST`
---| `UIC_DYNAMIC_ACTIONBAR`
---| `UIC_ENCHANT`
---| `UIC_ENTER_SECOND_PASSWORD`
---| `UIC_EQUIP_SLOT_REINFORCE`
---| `UIC_EQUIP_SLOT_REINFORCE_TAB`
---| `UIC_EVENT_CENTER`
---| `UIC_EXIT_GAME`
---| `UIC_EXPAND_INVENTORY`
---| `UIC_EXPAND_JOB`
---| `UIC_EXPEDITION`
---| `UIC_EXPEDITION_GUILD_FUNCTION_CHANGE_BUFF`
---| `UIC_FAMILY`
---| `UIC_FOLLOW`
---| `UIC_FORCE_ATTACK`
---| `UIC_FRIEND`
---| `UIC_GAME_EXIT_FRAME`
---| `UIC_GAME_TOOLTIP_WND`
---| `UIC_GUILD_BANK`
---| `UIC_HERO`
---| `UIC_HERO_ELECTION`
---| `UIC_HIDDEN_QUEST`
---| `UIC_INGAME_SHOP`
---| `UIC_INTERACT_SECOND_PASSWORD`
---| `UIC_ITEM_GUIDE`
---| `UIC_ITEM_LOCK`
---| `UIC_ITEM_REPAIR`
---| `UIC_LOCAL_DEVELOPMENT_BOARD`
---| `UIC_LOOK_CONVERT`
---| `UIC_LOOT_GACHA`
---| `UIC_MAIL`
---| `UIC_MAIN_ACTION_BAR`
---| `UIC_MAKE_CRAFT_ORDER`
---| `UIC_MARKET_PRICE`
---| `UIC_MEGAPHONE`
---| `UIC_MODE_ACTIONBAR`
---| `UIC_MY_FARM_INFO`
---| `UIC_NATION`
---| `UIC_NOTIFY_ACTABILITY`
---| `UIC_NOTIFY_SKILL`
---| `UIC_OPTIMIZATION`
---| `UIC_OPTION_FRAME`
---| `UIC_PARTY`
---| `UIC_PLAYER_EQUIPMENT`
---| `UIC_PLAYER_UNITFRAME`
---| `UIC_PREMIUM`
---| `UIC_QUEST_CINEMA_FADE_WND`
---| `UIC_QUEST_CINEMA_WND`
---| `UIC_QUEST_LIST`
---| `UIC_QUEST_NOTIFIER`
---| `UIC_RAID`
---| `UIC_RAID_RECRUIT`
---| `UIC_RAID_TEAM_MANAGER`
---| `UIC_RANK`
---| `UIC_RANK_LOCAL_VIEW`
---| `UIC_RECOVER_EXP`
---| `UIC_RENAME_EXPEDITION`
---| `UIC_REPORT_BAD_USER`
---| `UIC_REQUEST_BATTLEFIELD`
---| `UIC_RESIDENT_TOWNHALL`
---| `UIC_RETURN_ACCOUNT_REWARD_WND`
---| `UIC_ROSTER_MANAGER_WND`
---| `UIC_SCHEDULE_ITEM`
---| `UIC_SELECT_CHARACTER`
---| `UIC_SET_SECOND_PASSWORD`
---| `UIC_SHORTCUT_ACTIONBAR`
---| `UIC_SIEGE_RAID_REGISTER_WND`
---| `UIC_SIEGE_RAID_TEAM_MEMBER_LIST_WND`
---| `UIC_SKILL`
---| `UIC_SLAVE_EQUIPMENT`
---| `UIC_SPECIALTY_BUY`
---| `UIC_SPECIALTY_INFO`
---| `UIC_SPECIALTY_SELL`
---| `UIC_SQUAD`
---| `UIC_SQUAD_MINIVIEW`
---| `UIC_STABLER`
---| `UIC_STORE`
---| `UIC_SYSTEM_CONFIG_FRAME`
---| `UIC_TARGET_EQUIPMENT`
---| `UIC_TARGET_UNITFRAME`
---| `UIC_TGOS`
---| `UIC_TRADE`
---| `UIC_TRADER`
---| `UIC_TRADE_GOOD_PRICE_INFORMATION`
---| `UIC_UI_AVI`
---| `UIC_WEB_HELP`
---| `UIC_WEB_MESSENGER`
---| `UIC_WEB_PLAY_DIARY`
---| `UIC_WEB_PLAY_DIARY_INSTANCE`
---| `UIC_WEB_WIKI`
---| `UIC_WHISPER`
---| `UIC_WORLDMAP`

---```
---EscMenuButtonData { path = "addon/manager/manager_icon.dds", x = 75, y = 0, w = 15, h = 15 }
---```
---@class EscMenuButtonData
---@field path string
---@field x? number
---@field y? number
---@field w number 25
---@field h number 25

---```
---AddonInfo { name = "testing", enabled = true }
---```
---@class AddonInfo
---@field name string
---@field enabled boolean

---@class WidgetOld

---RGBA color with values restricted between 0 to 1.
---```
---RGBAColor { r: number, g: number, b: number, a: number }
---```
---@class RGBAColor : number[]
---@field [1] number Red (0 to 1)
---@field [2] number Green (0 to 1)
---@field [3] number Blue (0 to 1)
---@field [4] number Alpha (0 to 1)

---```
---Time { year = 0, month = 0, day = 0, hour = 0, minute = 0, second = 0 }
---```
---@class Time
---@field year number
---@field month number
---@field day number
---@field hour number
---@field minute number
---@field second number

---```
---TextureColors { [string]: RGBAColor }
---```
---@class TextureColors
---@field [string] RGBAColor

---
---```
---TextureColorKey { r, g, b }
---```
---@class TextureColorKey
---@field [1] number Red (0 to 1)
---@field [2] number Green (0 to 1)
---@field [3] number Blue (0 to 1)

---```
---TextureCoords { x, y, width, height }
---```
---@class TextureCoords
---@field [1] number x
---@field [2] number y
---@field [3] number width
---@field [4] number height

---@class TextureInset
---@field [1] number leftPadding
---@field [2] number topPadding
---@field [3] number rightPadding
---@field [4] number bottomPadding

---@class TextureDimensions
---@field [1] number resized width
---@field [2] number resized height

---@class TextureData
---@field offset number[]
---@field colors TextureColors
---@field colorKey TextureColorKey
---@field coords TextureCoords
---@field inset TextureInset
---@field extent TextureDimensions

---```
---TextureKeyData { width = 0, height = 0, keys = { key = value }}
---```
---@class TextureKeyData
---@field width number
---@field height number
---@field keys table

---```
---ScreenResolution { x = 1920, y = 1080, scale = 1 }
---```
---@class ScreenResolution
---@field x number width of screen
---@field y number height of screen
---@field scale number 

---```
---{ x = 0, y = 0, width = 0, height = 0 }
---```
---@class Bound
---@field x number
---@field y number
---@field width number unscaled width
---@field height number unscaled height

---```
---UIBound { screenResolution = { x = 1920, y = 1080, scale = 1 }, bound = { x = 0, y = 0, width = 0, height = 0 } }
---```
---@class UIBound
---@field screenResolution ScreenResolution
---@field bound Bound

---```
---Vec3 { x = 0, y = 0, z = 0 }
---```
---@class Vec3
---@field x number
---@field y number
---@field z number

---```
---VirtualMemoryStats { workingSet = 0, usage = 0 }
---```
---@class VirtualMemoryStats 
---@field workingSet number
---@field usage number

---```
---FontSizeList { default = 13, small = 11, middle = 13, large = 15, cinema = 26, xlarge = 18, xxlarge = 22 }
---```
---@class FontSizeList
---@field default number
---@field small number
---@field middle number
---@field large number
---@field cinema number
---@field xlarge number
---@field xxlarge number

--- X2Ability

---```
---ActabilityInfo { name = "Alchemy", type = 1, point = 0, modifyPoint = 0, grade = 0 }
---```
---@class ActabilityInfo
---@field name string
---@field type number
---@field point number
---@field modifyPoint number
---@field grade number

---As of 6/10/2025 only `BIK_DESCRIPTION` appears to work.
---@alias BIK number
---| `BIK_DESCRIPTION`
---| `BIK_RUNTIME_ALL` Broken
---| `BIK_RUNTIME_DURATION` Broken
---| `BIK_RUNTIME_MINE` Broken
---| `BIK_RUNTIME_STACK` Broken
---| `BIK_RUNTIME_TIMELEFT` Broken

--- 

--- X2Bag

---@alias BAGID 1


--- X2Chat

---@alias CMF
---| `CMF_ACQ_CONSUME_GROUP`
---| `CMF_ADDED_ITEM_GROUP`
---| `CMF_ADDED_ITEM_SELF`
---| `CMF_ADDED_ITEM_TEAM`
---| `CMF_ALL_SERVER`
---| `CMF_BEGIN_USE`
---| `CMF_BEHAVIOR_RESULT`
---| `CMF_BIG_MEGAPHONE`
---| `CMF_CHANNEL_INFO`
---| `CMF_COMBAT_DEAD`
---| `CMF_COMBAT_DST_GROUP`
---| `CMF_COMBAT_DST_OTHER`
---| `CMF_COMBAT_DST_SELF`
---| `CMF_COMBAT_ENVIRONMENTAL_DMANAGE`
---| `CMF_COMBAT_MELEE_DAMAGE`
---| `CMF_COMBAT_MELEE_GROUP`
---| `CMF_COMBAT_MELEE_MISSED`
---| `CMF_COMBAT_SPELL_AURA`
---| `CMF_COMBAT_SPELL_CAST`
---| `CMF_COMBAT_SPELL_DAMAGE`
---| `CMF_COMBAT_SPELL_ENERGIZE`
---| `CMF_COMBAT_SPELL_GROUP`
---| `CMF_COMBAT_SPELL_HEALED`
---| `CMF_COMBAT_SPELL_MISSED`
---| `CMF_COMBAT_SRC_GROUP`
---| `CMF_COMBAT_SRC_OTHER`
---| `CMF_COMBAT_SRC_SELF`
---| `CMF_COMMUNITY`
---| `CMF_CONNECT_ALERT`
---| `CMF_CONNECT_EXPEDITION`
---| `CMF_CONNECT_FAMILY`
---| `CMF_CONNECT_FRIEND`
---| `CMF_DE`
---| `CMF_DOMINION_AND_SIEGE_INFO`
---| `CMF_EMOTIOIN_EXPRESS`
---| `CMF_END_USE`
---| `CMF_EN_SG`
---| `CMF_EN_US`
---| `CMF_ETC_GROUP`
---| `CMF_EXPEDITION`
---| `CMF_FACTION`
---| `CMF_FAMILY`
---| `CMF_FIND_PARTY`
---| `CMF_FR`
---| `CMF_HERO_SEASON_UPDATED`
---| `CMF_IND`
---| `CMF_JA`
---| `CMF_KO`
---| `CMF_LANG_BEGIN`
---| `CMF_LANG_END`
---| `CMF_LOCALE_SERVER`
---| `CMF_LOOT_METHOD_CHANGED`
---| `CMF_NONE`
---| `CMF_NOTICE`
---| `CMF_OTHER_CONTINENT`
---| `CMF_PARTY`
---| `CMF_PARTY_AND_RAID_INFO`
---| `CMF_PLAY_MUSIC`
---| `CMF_QUEST_INFO`
---| `CMF_RACE`
---| `CMF_RAID`
---| `CMF_RAID_COMMAND`
---| `CMF_RU`
---| `CMF_SAY`
---| `CMF_SELF_CONTRIBUTION_POINT_CHANGED`
---| `CMF_SELF_HONOR_POINT_CHANGED`
---| `CMF_SELF_LEADERSHIP_POINT_CHANGED`
---| `CMF_SELF_LIVING_POINT_CHANGED`
---| `CMF_SELF_MONEY_CHANGED`
---| `CMF_SELF_SKILL_INFO`
---| `CMF_SMALL_MEGAPHONE`
---| `CMF_SQUAD`
---| `CMF_SYSTEM`
---| `CMF_TH`
---| `CMF_TRADE`
---| `CMF_TRADE_STORE_MSG`
---| `CMF_TRIAL`
---| `CMF_WHISPER`
---| `CMF_ZH_CN`
---| `CMF_ZH_TW`
---| `CMF_ZONE`

--- X2Craft

---@class CraftBaseInfo
---@field orderable boolean
---@field cost number
---@field skill_type number
---@field laborpower_satisfied boolean
---@field required_actability_name string
---@field cost_satisfied boolean
---@field require_doodad number
---@field doodad_name string
---@field needed_lp number
---@field required_actability_point number
---@field actability_satisfied boolean
---@field title string
---@field craft_type number
---@field consume_lp number
---@field recommend_level number
---@field required_actability_type number
---@field use_only_actability boolean

---@class CraftProductInfo
---@field productGrade number
---@field itemType number
---@field amount number
---@field item_name string
---@field success_rate number
---@field useGrade boolean

--- X2Equipment

---@alias EquipSlot
---| `ES_ARMS`
---| `ES_BACK`
---| `ES_BACKPACK`
---| `ES_BEARD`
---| `ES_BODY`
---| `ES_CHEST`
---| `ES_COSPLAY`
---| `ES_COSPLAYLOOKS`
---| `ES_EAR_1`
---| `ES_EAR_2`
---| `ES_FACE`
---| `ES_FEET`
---| `ES_FINGER_1`
---| `ES_FINGER_2`
---| `ES_GLASSES`
---| `ES_HAIR`
---| `ES_HANDS`
---| `ES_HEAD`
---| `ES_HORNS`
---| `ES_INVALID`
---| `ES_LEGS`
---| `ES_MAINHAND`
---| `ES_MUSICAL`
---| `ES_NECK`
---| `ES_OFFHAND`
---| `ES_RANGED`
---| `ES_TAIL`
---| `ES_UNDERPANTS`
---| `ES_UNDERSHIRT`
---| `ES_WAIST`

--- X2Item

---@alias LinkKind
---| `"coffer"`
---| `"auction"`

---Values can be added together to get more information.
---@alias IIK
---| `IIK_CATEGORY`
---| `IIK_CONSUME_ITEM`
---| `IIK_GRADE`
---| `IIK_GRADE_STR`
---| `IIK_IMPL`
---| `IIK_NAME`
---| `IIK_SELL`
---| `IIK_SOCKET_MODIFIER`
---| `IIK_STACK`
---| `IIK_TYPE`

--- X2Locale

---@alias LocaleIndex
---| `0`
---| `1`
---| `2` en_us
---| `3`
---| `4`
---| `5`
---| `6`
---| `7`
---| `8`
---| `9`
---| `10`

---@alias UI_TEXT
---| `ABILITY_CATEGORY_DESCRIPTION_TEXT`
---| `ABILITY_CATEGORY_TEXT`
---| `ABILITY_CHANGER_TEXT`
---| `ATTRIBUTE_TEXT`
---| `ATTRIBUTE_VARIATION_TEXT`
---| `AUCTION_TEXT`
---| `BATTLE_FIELD_TEXT`
---| `BEAUTYSHOP_TEXT`
---| `CASTING_BAR_TEXT`
---| `CHARACTER_CREATE_TEXT`
---| `CHARACTER_POPUP_SUBTITLE_TEXT`
---| `CHARACTER_POPUP_SUBTITLE_TOOLTIP_TEXT`
---| `CHARACTER_SELECT_TEXT`
---| `CHARACTER_SUBTITLE_INFO_TOOLTIP_TEXT`
---| `CHARACTER_SUBTITLE_TEXT`
---| `CHARACTER_SUBTITLE_TOOLTIP_TEXT`
---| `CHARACTER_TITLE_TEXT`
---| `CHAT_CHANNEL_TEXT`
---| `CHAT_COMBAT_LOG_TEXT`
---| `CHAT_CREATE_TAB_TEXT`
---| `CHAT_FORCE_ATTACK_TEXT`
---| `CHAT_LIST_TEXT`
---| `CHAT_SYSTEM_TEXT`
---| `COMBAT_MESSAGE_TEXT`
---| `COMBAT_TEXT`
---| `COMBINED_ABILITY_NAME_TEXT`
---| `COMMON_TEXT`
---| `COMMUNITY_TEXT`
---| `COMPOSITION_TEXT`
---| `CRAFT_TEXT`
---| `CUSTOMIZING_TEXT`
---| `DATE_TIME_TEXT`
---| `DUEL_TEXT`
---| `EQUIP_SLOT_TYPE_TEXT`
---| `EXPEDITION_TEXT`
---| `FACTION_TEXT`
---| `FARM_TEXT`
---| `GENDER_TEXT`
---| `GRAVE_YARD_TEXT`
---| `HERO_TEXT`
---| `HONOR_POINT_WAR_TEXT`
---| `HOUSING_PERMISSIONS_TEXT`
---| `HOUSING_TEXT`
---| `INFOBAR_MENU_TEXT`
---| `INFOBAR_MENU_TIP_TEXT`
---| `INGAMESHOP_TEXT`
---| `INSTANT_GAME_TEXT`
---| `INVEN_TEXT`
---| `ITEM_LOOK_CONVERT_TEXT`
---| `KEY_BINDING_TEXT`
---| `LEARNING_TEXT`
---| `LEVEL_CHANGED_TEXT`
---| `LOADING_TEXT`
---| `LOGIN_CROWDED_TEXT`
---| `LOGIN_DELETE_TEXT`
---| `LOGIN_TEXT`
---| `LOOT_METHOD_TEXT`
---| `LOOT_TEXT`
---| `MAIL_TEXT`
---| `MAP_TEXT`
---| `MONEY_TEXT`
---| `MSG_BOX_BODY_TEXT`
---| `MSG_BOX_BTN_TEXT`
---| `MSG_BOX_TITLE_TEXT`
---| `MUSIC_TEXT`
---| `NATION_TEXT`
---| `OPTION_TEXT`
---| `PARTY_TEXT`
---| `PERIOD_TIME_TEXT`
---| `PET_TEXT`
---| `PHYSICAL_ENCHANT_TEXT`
---| `PLAYER_POPUP_TEXT`
---| `PORTAL_TEXT`
---| `PREMIUM_TEXT`
---| `PRIEST_TEXT`
---| `PROTECT_SENSITIVE_OPERATION_TEXT`
---| `QUEST_ACT_OBJ_PTN_TEXT`
---| `QUEST_ACT_OBJ_TEXT`
---| `QUEST_CONDITION_TEXT`
---| `QUEST_DISTANCE_TEXT`
---| `QUEST_INTERACTION_TEXT`
---| `QUEST_OBJ_STATUS_TEXT`
---| `QUEST_SPHERE_TEXT`
---| `QUEST_STATUS_TEXT`
---| `QUEST_TEXT`
---| `RACE_DETAIL_DESCRIPTION_TEXT`
---| `RACE_TEXT`
---| `RAID_TEXT`
---| `RANKING_TEXT`
---| `REPAIR_TEXT`
---| `RESTRICT_TEXT`
---| `SECOND_PASSWORD_TEXT`
---| `SERVER_TEXT`
---| `SKILL_TEXT`
---| `SKILL_TRAINING_MSG_TEXT`
---| `SLAVE_TEXT`
---| `STABLER_TEXT`
---| `STORE_TEXT`
---| `TARGET_POPUP_TEXT`
---| `TEAM_TEXT`
---| `TERRITORY_TEXT`
---| `TOOLTIP_TEXT`
---| `TRADE_TEXT`
---| `TRIAL_TEXT`
---| `TUTORIAL_TEXT`
---| `UCC_TEXT`
---| `UNIT_FRAME_TEXT`
---| `UNIT_GRADE_TEXT`
---| `UNIT_KIND_TEXT`
---| `UTIL_TEXT`
---| `WEB_TEXT`
---| `WINDOW_TITLE_TEXT`

--- X2Option

---@alias OISLT
---| `OISLT_CHARACTER`
---| `OISLT_CHARACTER_MODE`
---| `OISLT_SYSTEM` This appears to save it to the system but unable to get again once I restart (C:\ArcheRage\Documents\USER_MUSIC_DISABLE_SELF\udf\.+.sst)

---```
---AAFormat { txaa = 1, samples = 1, quality = 1, desc = "" }
---```
---@class AAFormat
---@field txaa number
---@field samples number
---@field quality number
---@field desc string

---@alias OIT
---| `OIT_ACTION_BAR_LOCK`
---| `OIT_AUTO_ENEMY_TARGETING`
---| `OIT_AUTO_USE_ONLY_MY_PORTAL`
---| `OIT_BASIC_CURSOR_SHAPE`
---| `OIT_CAMERA_USE_SHAKE`
---| `OIT_CLICK_TO_MOVE`
---| `OIT_COMBAT_MSG_DISPLAY_SHIP_COLLISION`
---| `OIT_COMBAT_MSG_LEVEL`
---| `OIT_COMBAT_MSG_VISIBILITY`
---| `OIT_CR_INVERT_X_AXIS`
---| `OIT_CR_INVERT_Y_AXIS`
---| `OIT_CR_SENSITIVITY`
---| `OIT_CURSOR_SIZE`
---| `OIT_CUSTOM_CAMERA_MAX_DIST`
---| `OIT_CUSTOM_FOV`
---| `OIT_CUSTOM_ZOOM_SENSITIVITY`
---| `OIT_DECORATION_SMART_POSITIONING`
---| `OIT_DOODAD_SMART_POSITIONING`
---| `OIT_E_CUSTOM_CLONE_MODE`
---| `OIT_E_CUSTOM_MAX_CLONE_MODEL`
---| `OIT_E_CUSTOM_MAX_MODEL`
---| `OIT_E_ZONEWEATHEREFFECT`
---| `OIT_FIRE_ACTION_ON_BUTTON_DOWN`
---| `OIT_FIXEDTOOLTIPPOSITION`
---| `OIT_GIVEN_QUEST_DISTANCE_DISPLAY_MODE`
---| `OIT_GLIDER_START_WITH_DOUBLE_JUMP`
---| `OIT_G_HIDE_TUTORIAL`
---| `OIT_G_IGNORE_CHAT_FILTER`
---| `OIT_G_IGNORE_DUEL_INVITE`
---| `OIT_G_IGNORE_EXPEDITION_INVITE`
---| `OIT_G_IGNORE_FAMILY_INVITE`
---| `OIT_G_IGNORE_JURY_INVITE`
---| `OIT_G_IGNORE_PARTY_INVITE`
---| `OIT_G_IGNORE_RAID_INVITE`
---| `OIT_G_IGNORE_RAID_JOINT`
---| `OIT_G_IGNORE_SQUAD_INVITE`
---| `OIT_G_IGNORE_TRADE_INVITE`
---| `OIT_G_IGNORE_WHISPER_INVITE`
---| `OIT_G_SHOW_LOOT_WINDOW`
---| `OIT_G_USE_CHAT_TIME_STAMP`
---| `OIT_ITEM_MAKER_INFO_SHOW_TOOLTIP`
---| `OIT_MASTERGRAHICQUALITY`
---| `OIT_NAME_TAG_APPELLATION_SHOW`
---| `OIT_NAME_TAG_EXPEDITIONFAMILY_SHOW`
---| `OIT_NAME_TAG_EXPEDITION_SHOW`
---| `OIT_NAME_TAG_FACTION_SELECTION`
---| `OIT_NAME_TAG_FACTION_SHOW`
---| `OIT_NAME_TAG_FRIENDLY_MATE_SHOW`
---| `OIT_NAME_TAG_FRIENDLY_SHOW`
---| `OIT_NAME_TAG_HOSTILE_MATE_SHOW`
---| `OIT_NAME_TAG_HOSTILE_SHOW`
---| `OIT_NAME_TAG_HP_SHOW`
---| `OIT_NAME_TAG_MODE`
---| `OIT_NAME_TAG_MY_MATE_SHOW`
---| `OIT_NAME_TAG_NPC_SHOW`
---| `OIT_NAME_TAG_PARTY_SHOW`
---| `OIT_NAME_TAG_SELF_ENABLE`
---| `OIT_NEXT_OPTION_SOUND`
---| `OIT_NEXT_R_DRIVER`
---| `OIT_NEXT_R_MULTITHREADED`
---| `OIT_NEXT_SYS_SPEC_FULL`
---| `OIT_OPTION_ANIMATION`
---| `OIT_OPTION_ANTI_ALIASING`
---| `OIT_OPTION_CAMERA_FOV_SET`
---| `OIT_OPTION_CHARACTER_LOD`
---| `OIT_OPTION_CHARACTER_PRIVACY_STATUS`
---| `OIT_OPTION_CUSTOM_ADDON_FONTS`
---| `OIT_OPTION_CUSTOM_ADDON_UI`
---| `OIT_OPTION_CUSTOM_SKILL_QUEUE`
---| `OIT_OPTION_DISABLE_PRIVATE_MESSAGE_MUSIC`
---| `OIT_OPTION_EFFECT`
---| `OIT_OPTION_ENABLE_COMBAT_CHAT_LOG`
---| `OIT_OPTION_ENABLE_MISC_CHAT_LOG`
---| `OIT_OPTION_GAME_LOGS_LIFE_TIME`
---| `OIT_OPTION_HIDE_BLOODLUST_MODE`
---| `OIT_OPTION_HIDE_ENCHANT_BROADCAST`
---| `OIT_OPTION_HIDE_MOBILIZATION_ORDER`
---| `OIT_OPTION_ITEM_MOUNT_ONLY_MY_PET`
---| `OIT_OPTION_MAP_GIVEN_QUEST_DISTANCE`
---| `OIT_OPTION_OPTIMIZATION_ENABLE`
---| `OIT_OPTION_OVERHEAD_MARKER_FIXED_SIZE`
---| `OIT_OPTION_SHADER_QUALITY`
---| `OIT_OPTION_SHADOW_DIST`
---| `OIT_OPTION_SHADOW_VIEW_DIST_RATIO`
---| `OIT_OPTION_SHADOW_VIEW_DIST_RATIO_CHARACTER`
---| `OIT_OPTION_SHOW_COMBAT_RESOURCE_WINDOW`
---| `OIT_OPTION_SKILL_ALERT_ENABLE`
---| `OIT_OPTION_SKILL_ALERT_POSITION`
---| `OIT_OPTION_TERRAIN_DETAIL`
---| `OIT_OPTION_TERRAIN_LOD`
---| `OIT_OPTION_TEXTURE_BG`
---| `OIT_OPTION_TEXTURE_CHARACTER`
---| `OIT_OPTION_USE_CLOUD`
---| `OIT_OPTION_USE_DOF`
---| `OIT_OPTION_USE_HDR`
---| `OIT_OPTION_USE_KR_FONTS`
---| `OIT_OPTION_USE_SHADOW`
---| `OIT_OPTION_USE_WATER_REFLECTION`
---| `OIT_OPTION_VIEW_DISTANCE`
---| `OIT_OPTION_VIEW_DIST_RATIO`
---| `OIT_OPTION_VIEW_DIST_RATIO_VEGETATION`
---| `OIT_OPTION_VOLUMETRIC_EFFECT`
---| `OIT_OPTION_WATER`
---| `OIT_OPTION_WEAPON_EFFECT`
---| `OIT_R_DESIREHEIGHT`
---| `OIT_R_DESIREWIDTH`
---| `OIT_R_FULLSCREEN`
---| `OIT_R_GAMMA`
---| `OIT_R_PIXELSYNC`
---| `OIT_R_VSYNC`
---| `OIT_SHOWACTIONBAR_1`
---| `OIT_SHOWACTIONBAR_2`
---| `OIT_SHOWACTIONBAR_3`
---| `OIT_SHOWACTIONBAR_4`
---| `OIT_SHOWACTIONBAR_5`
---| `OIT_SHOWACTIONBAR_6`
---| `OIT_SHOWBUFFDURATION`
---| `OIT_SHOWCHATBUBBLE`
---| `OIT_SHOWEMPTYBAGSLOTCOUNTER`
---| `OIT_SHOWFPS`
---| `OIT_SHOWGAMETIME`
---| `OIT_SHOWHEATLTHNUMBER`
---| `OIT_SHOWMAGICPOINTNUMBER`
---| `OIT_SHOWPLAYERFRAMELIFEALERTEFFECT`
---| `OIT_SHOWSERVERTIME`
---| `OIT_SHOWTARGETCASTINGBAR`
---| `OIT_SHOWTARGETTOTARGETCASTINGBAR`
---| `OIT_SHOW_GUIDEDECAL`
---| `OIT_SKILL_DETAIL_DAMAGE_SHOW_TOOLTIP`
---| `OIT_SKILL_SYNERGY_INFO_SHOW_TOOLTIP`
---| `OIT_SLOT_COOLDOWN_VISIBLE`
---| `OIT_SMART_GROUND_TARGETING`
---| `OIT_SOUND_MOOD_COMBAT_ENABLE`
---| `OIT_SYS_MAX_FPS`
---| `OIT_SYS_USE_LIMIT_FPS`
---| `OIT_S_CINEMAVOLUME`
---| `OIT_S_GAMEMASTERVOLUME`
---| `OIT_S_MIDIVOLUME`
---| `OIT_S_MUSICVOLUME`
---| `OIT_S_SFXVOLUME`
---| `OIT_S_VEHCLEMUSICVOLUME`
---| `OIT_UI_SCALE`
---| `OIT_USEQUESTDIRECTINGCLOSEUPCAMERA`
---| `OIT_USER_MUSIC_DISABLE_OTHERS`
---| `OIT_USER_MUSIC_DISABLE_SELF`
---| `OIT_USE_AUTO_REGIST_DISTRICT`
---| `OIT_USE_CELERITY_WITH_DOUBLE_FORWARD`
---| `OIT_VISIBLEMYEQUIPINFO`

---```
---OptionInfo { tooltip = "", title = "", restart = false }
---```
---@class OptionInfo
---@field tooltip string
---@field title string
---@field restart boolean

---```
---SubOptionItem { optionId = 1, value = "" }
---```
---@class SubOptionItem
---@field optionId number
---@field value number


--- X2Player

---```
---AppellationBuffInfo { path = "", description = "", category = "", tipType = "", buff_id = 0, name = "" }
---```
---@class AppellationBuffInfo
---@field path string
---@field description string
---@field category string
---@field tipType string
---@field buff_id number
---@field name string

---```
---AppellationChangeItemInfo { has = 0, enough = false, need = 1, itemType = 0 }
---```
---@class AppellationChangeItemInfo
---@field has number
---@field enough boolean
---@field need number
---@field itemType number

---```
---AppellationMyLevelInfo { minExp = 0, maxlevel = 8, maxExp = 0, exp = 0 }
---```
---@class AppellationMyLevelInfo
---@field minExp number
---@field maxlevel number
---@field maxExp number
---@field exp number

---
---```
---AppellationMyStamp { id = 0, path = "" }
---```
---@class AppellationMyStamp
---@field id number
---@field path string

---@class StampInfo: AppellationMyStamp
---@field canEquip number
---@field name string
---@field modifier table
---@field effectDescription string
---@field reqLevel number

---@class AppellationRouteInfo
---@field routePopup number
---@field kind number
---@field routeDesc string
---@field type number

---@alias APPELATION_ROUTE_TYPE
---| `APPELATION_ROUTE_TYPE_ACHIEVEMENTS`
---| `APPELATION_ROUTE_TYPE_ETC`
---| `APPELATION_ROUTE_TYPE_HIDDEN`
---| `APPELATION_ROUTE_TYPE_MAX`
---| `APPELATION_ROUTE_TYPE_MERCHANT_PACKS`
---| `APPELATION_ROUTE_TYPE_QUEST_CONTEXTS`

---```
---Appellation {
---  [1]: number, -- APPELLATION_INFO.TYPE
---  [2]: number, -- APPELLATION_INFO.NAME
---  [3]: number, -- APPELLATION_INFO.GRADE
---  [4]: number, -- APPELLATION_INFO.ISHAVE
---  [5]: number, -- APPELLATION_INFO.ORDER
---  [6]: number, -- APPELLATION_INFO.BUFF_INFO
--- }
---```
---@class Appellation
---@field [1] number APPELLATION_INFO.TYPE
---@field [2] string APPELLATION_INFO.NAME
---@field [3] number APPELLATION_INFO.GRADE
---@field [4] number APPELLATION_INFO.ISHAVE
---@field [5] number APPELLATION_INFO.ORDER
---@field [6] AppellationBuffInfo? APPELLATION_INFO.BUFF_INFO

---```
---StampChangeItemInfo { has = 0, enough = false, need = 1, itemType = 44584 }
---```
---@class StampChangeItemInfo
---@field has number
---@field enough boolean
---@field need number
---@field itemType number

---```
---UnitAppellationRoute { key = 1, value = "" }
---```
---@class UnitAppellationRoute
---@field key number
---@field value string

--- X2Skill

---@class SynergyIconInfo
---@field conditionbuffkind boolean
---@field conditionicon string
---@field resulticon string
---@field resultbuffkind boolean
---@field desc string

---@class SkillTooltip
---@field synergyIconInfo SynergyIconInfo[]
---@field path string
---@field description string
---@field maxCombatResource number
---@field mana number
---@field maxRange number
---@field category string
---@field firstLearnLevel number
---@field abilityLevel number
---@field skillPoints number
---@field tipType string
---@field levelStep number
---@field type number
---@field meleeDpsMultiplier number
---@field isRaceSkill boolean
---@field minCombatResource number
---@field targetAreaRadius number
---@field minRange number
---@field ability string
---@field show boolean
---@field channeling number
---@field name string
---@field learnLevel number
---@field heirSkillName number
---@field casting number
---@field cooldown number
---@field skillLevel number

---Values can be added together to get more information.
---@alias SIK
---| `SIK_DESCRIPTION`
---| `4` Not defined but can be used to get almost everything thats not the description.

--- X2Store

---```
---ZoneInfo { continentName = "Nuia", zoneGroupName = "Gweonid Forest", id = 1 }
---```
---@class ZoneInfo
---@field continentName string
---@field zoneGroupName string
---@field id number

--- X2Team

---@alias TEAM_ROLE
---| `TMROLE_DEALER`
---| `TMROLE_HEALER`
---| `TMROLE_NONE`
---| `TMROLE_RANGED_DEALER`
---| `TMROLE_TANKER`

--- X2Unit

---```
---TargetAbilityTemplate { level = 55, name = "wild", index = 6 }
---```
---@class TargetAbilityTemplate
---@field level number
---@field name string
---@field index number

---@class UnitClass
---@field [1] number
---@field [2] number
---@field [3] number

---@class UnitInfo
---@field expeditionName string
---@field type string
---@field class UnitClass
---@field hp string
---@field name string
---@field faction string
---@field family_name string
---@field level number
---@field heirLevel number
---@field maxHp string

---```
---BuffInfo { stack = 1, path = "", timeLeft = 0, buff_id = 0 }
---```
---@class BuffInfo
---@field stack number
---@field path string
---@field timeLeft number
---@field buff_id number

---This inherits from BuffInfo but also shares all of AppellationBuffInfo, these will need to rewritten and extract the
---common fields to their own class
---@class BuffTooltip: BuffInfo
---@field description string
---@field tipType string
---@field mine boolean
---@field name string
---@field category string
---@field timeUnit string
---@field duration number

---@class CastingInfo
---@field currCastingTime number
---@field castingTime number
---@field castingUseable boolean
---@field showTargetCastingTime boolean
---@field spellName string

---```
---UnitDistance { over_distance = false, distance = 1 }
---```
---@class UnitDistance
---@field over_distance boolean
---@field distance number

--- X2Map

---@class ZoneStateInfo
---@field localDevelopmentName string
---@field isSiegeZone boolean
---@field localDevelopmentStep number
---@field isNuiaProtectedZone boolean
---@field warChaos boolean
---@field isLocalDevelopment boolean
---@field isConflictZone boolean
---@field conflictState number
---@field nonPeaceState boolean
---@field isFestivalZone boolean
---@field isCurrentZone boolean
---@field isInstanceZone boolean
---@field isPeaceZone boolean
---@field isHariharaProtectedZone boolean
---@field zoneName string

--- X2Achievement

---@alias ACHIEVEMENT_KIND
---| `EAK_ACHIEVEMENT`
---| `EAK_ARCHERAGE`
---| `EAK_COLLECTION`
---| `EAK_RACIAL_MISSION`

---@class RewardItemInfo
---@field itemType number
---@field count number

---@class RewardInfo
---@field item RewardItemInfo

---@class AppellationInfo
---@field name string
---@field iconPath string

---@class AchievementInfo
---@field current number
---@field subCategoryType number
---@field complete boolean
---@field completeNum number
---@field tracing boolean
---@field subCategoryName string
---@field achievementType number
---@field achievementKind number
---@field type number
---@field grade number
---@field desc string
---@field isHidden boolean
---@field canProgress boolean
---@field summary string
---@field highRank boolean
---@field name string
---@field iconPath string
---@field categoryName string
---@field reward RewardInfo
---@field appellation AppellationInfo

---@alias ACHIEVEMENT_FILTER
---| `AF_ALL`
---| `AF_COMPLETE` Doesnt work. Is the same as AF_ALL.
---| `AF_INVALID` Doesnt work. Is the same as AF_ALL.
---| `AF_TRACING`
---| `AF_UNCOMPLETE` Doesnt work. Is the same as AF_ALL.

---@class AchievementSubCategory
---@field name string
---@field subCategoryType number

---@class AchievementLevelSubCategory: AchievementSubCategory
---@field isHeirLevelCategory boolean

---@class AchievementCategory
---@field subCategories AchievementSubCategory[]
---@field categoryType number
---@field name string

---```
---SubcategoryInfo {
--- isHeirLevelCategory = false, completedCount = 0. rewardAchievementType = 0,
--- totalCount = 0, name = "", desc = ""
---}
---```
---@class SubcategoryInfo
---@field isHeirLevelCategory boolean
---@field completedCount number
---@field rewardAchievementType number
---@field totalCount number
---@field name string
---@field desc string

---@alias TODAY_TYPE
---| `TADT_ARCHE_PASS`
---| `TADT_EXPEDITION`
---| `TADT_EXPEDITION_PUBLIC`
---| `TADT_FAMILY`
---| `TADT_HERO`
---| `TADT_MAX`
---| `TADT_TODAY`

---```
---TodayAssignmentInfoForChange {
--- init = false, levelMin = 0, iconPath = "", questType = 0, realStep = 0,
--- desc = "", sort = 0, levelMax = 0, status = 0, title = "", satisfy = false,
--- requireLevel = 0
---}
---```
---@class TodayAssignmentInfo
---@field init boolean
---@field levelMin number
---@field iconPath string
---@field questType number
---@field realStep number
---@field desc string
---@field sort number
---@field levelMax number
---@field status number
---@field title string
---@field satisfy boolean
---@field requireLevel number 

---@class AchievementSubList
---@field key number

--- X2Resident

---@alias HOUSING_LIST_FILTER
---| `HOUSING_LIST_FILTER_ALL`
---| `HOUSING_LIST_FILTER_FARM`
---| `HOUSING_LIST_FILTER_FLOATING`
---| `HOUSING_LIST_FILTER_HOUSE_NAME`
---| `HOUSING_LIST_FILTER_LARGE`
---| `HOUSING_LIST_FILTER_MANSION`
---| `HOUSING_LIST_FILTER_MEDIUM`
---| `HOUSING_LIST_FILTER_PUBLIC`
---| `HOUSING_LIST_FILTER_SELLER_NAME`
---| `HOUSING_LIST_FILTER_SMALL`
---| `HOUSING_LIST_FILTER_UNDERWATER_STRUCTURE`
---| `HOUSING_LIST_FILTER_WORKTABLE`

---@class ResidentBoardContent
---@field [1] string?
---@field [2] string?
---@field [3] string?
---@field [4] string?
---@field title string
---@field faction string

--- X2CombatResource

---@class CombatResource
---@field uiType number
---@field resource1Max number
---@field ability number
---@field resource1Current number
---@field recoveryResourceType number
---@field isDefaultResource boolean
---@field resource1ColorKey string
---@field resource2Max? number 
---@field resource2Current? number 
---@field resource2ColorKey? string 

---@class CombatResourceInfo: CombatResource
---@field tooltip string
---@field iconPath string
---@field groupType number
