---@meta _

BSS_GENDER_TRANSFERED = 1            -- api/X2Customizer BEAUTY_SHOP_STATUS
BSS_INVALID_PLACE = 2                -- api/X2Customizer BEAUTY_SHOP_STATUS
BSS_POSSIBLE = 0                     -- api/X2Customizer BEAUTY_SHOP_STATUS
CDR_DELETE_SUCCESS = 3               -- api/X2Customizer CUSTOMIZER_DATA_RESULT
CDR_ERROR_AS_INVALID_DATA = 7        -- api/X2Customizer CUSTOMIZER_DATA_RESULT
CDR_ERROR_AS_NOT_SELECT = 8          -- api/X2Customizer CUSTOMIZER_DATA_RESULT
CDR_ERROR_AS_NO_FILE = 5             -- api/X2Customizer CUSTOMIZER_DATA_RESULT
CDR_ERROR_AS_NO_FILE_NAME = 9        -- api/X2Customizer CUSTOMIZER_DATA_RESULT
CDR_ERROR_AS_NO_PATH = 4             -- api/X2Customizer CUSTOMIZER_DATA_RESULT
CDR_ERROR_AS_SAME_FILE = 6           -- api/X2Customizer CUSTOMIZER_DATA_RESULT
CDR_ERROR_UNSERVICEABILITY_WORD = 10 -- api/X2Customizer CUSTOMIZER_DATA_RESULT
CDR_INVALID_RESULT = 0               -- api/X2Customizer CUSTOMIZER_DATA_RESULT
CDR_LOAD_SUCCESS = 1                 -- api/X2Customizer CUSTOMIZER_DATA_RESULT
CDR_SAVE_SUCCESS = 2                 -- api/X2Customizer CUSTOMIZER_DATA_RESULT
---@class X2Customizer
X2Customizer = {}                    -- api/X2Customizer

---api/X2Customizer
---@alias BEAUTY_SHOP_STATUS
---| `BSS_GENDER_TRANSFERED`
---| `BSS_INVALID_PLACE`
---| `BSS_POSSIBLE`

---api/X2Customizer
---@alias CUSTOMIZER_DATA_RESULT
---| `CDR_DELETE_SUCCESS`
---| `CDR_ERROR_AS_INVALID_DATA`
---| `CDR_ERROR_AS_NOT_SELECT`
---| `CDR_ERROR_AS_NO_FILE`
---| `CDR_ERROR_AS_NO_FILE_NAME`
---| `CDR_ERROR_AS_NO_PATH`
---| `CDR_ERROR_AS_SAME_FILE`
---| `CDR_ERROR_UNSERVICEABILITY_WORD`
---| `CDR_INVALID_RESULT`
---| `CDR_LOAD_SUCCESS`
---| `CDR_SAVE_SUCCESS`
