---@meta _

IGLMC_BOSS = 4           -- api/X2ItemGuide ITEM_GUIDE_LOOT_MASTER_CATEGORY
IGLMC_CRAFT = 1          -- api/X2ItemGuide ITEM_GUIDE_LOOT_MASTER_CATEGORY
IGLMC_ETC = 5            -- api/X2ItemGuide ITEM_GUIDE_LOOT_MASTER_CATEGORY
IGLMC_EVENT = 7          -- api/X2ItemGuide ITEM_GUIDE_LOOT_MASTER_CATEGORY
IGLMC_INDUN = 3          -- api/X2ItemGuide ITEM_GUIDE_LOOT_MASTER_CATEGORY
IGLMC_INGAME_SHOP = 8    -- api/X2ItemGuide ITEM_GUIDE_LOOT_MASTER_CATEGORY
IGLMC_OTHER_CRAFT = 2    -- api/X2ItemGuide ITEM_GUIDE_LOOT_MASTER_CATEGORY
IGLMC_REBUILDING = 9     -- api/X2ItemGuide ITEM_GUIDE_LOOT_MASTER_CATEGORY
IGLMC_SHOP = 6           -- api/X2ItemGuide ITEM_GUIDE_LOOT_MASTER_CATEGORY
IGLMC_SOCKET_CHANGE = 10 -- api/X2ItemGuide ITEM_GUIDE_LOOT_MASTER_CATEGORY
---@class X2ItemGuide
X2ItemGuide = {}         -- api/X2ItemGuide

---api/X2ItemGuide
---@alias ITEM_GUIDE_LOOT_MASTER_CATEGORY
---| `IGLMC_BOSS`
---| `IGLMC_CRAFT`
---| `IGLMC_ETC`
---| `IGLMC_EVENT`
---| `IGLMC_INDUN`
---| `IGLMC_INGAME_SHOP`
---| `IGLMC_OTHER_CRAFT`
---| `IGLMC_REBUILDING`
---| `IGLMC_SHOP`
---| `IGLMC_SOCKET_CHANGE`
