---@meta _

ESFP_DONE = 1     -- api/X2SurveyForm ENUM_SURVEY_FORM_PERIOD
ESFP_EXPIERED = 2 -- api/X2SurveyForm ENUM_SURVEY_FORM_PERIOD
ESFP_INVALID = -1 -- api/X2SurveyForm ENUM_SURVEY_FORM_PERIOD
ESFP_NONE = 0     -- api/X2SurveyForm ENUM_SURVEY_FORM_PERIOD
ESFP_TODO = 3     -- api/X2SurveyForm ENUM_SURVEY_FORM_PERIOD
SFQK_CHECK = 2    -- api/X2SurveyForm SURVEY_FORM_QUESTION_KIND
SFQK_INVALID = 0  -- api/X2SurveyForm SURVEY_FORM_QUESTION_KIND
SFQK_RADIO = 1    -- api/X2SurveyForm SURVEY_FORM_QUESTION_KIND
---@class X2SurveyForm
X2SurveyForm = {} -- api/X2SurveyForm

-- api/X2SurveyForm
---@alias ENUM_SURVEY_FORM_PERIOD
---| `ESFP_DONE`
---| `ESFP_EXPIERED`
---| `ESFP_INVALID`
---| `ESFP_NONE`
---| `ESFP_TODO`

-- api/X2SurveyForm
---@alias SURVEY_FORM_QUESTION_KIND
---| `SFQK_CHECK`
---| `SFQK_INVALID`
---| `SFQK_RADIO`
