for object_name, object_id in pairs(OBJECT) do
  if true
  -- and object_name ~= "Textbox"
  -- and object_name ~= "TextStyle"
  -- and object_name ~= "Button"
  -- and object_name ~= "ColorDrawable"
  -- and object_name ~= "ImageDrawable"
  -- and object_name ~= "NinePartDrawable"
  and object_name ~= "Avi"
  then
    ADDON:ImportObject(object_id)
  end
end

local function log(...)
  local args = { ... }
  ADDON:ChatLog(dump(args))
end

---@generic T
---@param value T|EmptyTable|nil
---@return T
local function widgetassert(value)
  assert(value ~= nil, "Not set.")

  local notEmpty = next(value) ~= nil
  local hasMetatable = getmetatable(value) ~= nil
  assert(notEmpty and hasMetatable, "Did you forget to import the object?")

  return value
end

local file = open("temp/eventdump.txt", "w")

local function event(name, ...)
  local function handler(...)
    ADDON:ChatLog(name)
    local v, f = dump({ [name] = { ... } })

    file:write(v, "\n")

    if f ~= nil then
      file:write(f, "\n")
    end

    file:flush()
    -- log({ ... })
  end
  return handler
end

local eventCount = 0

function SetEventHandler(name)
  if eventCount < 240 then
    UI:SetEventHandler(name, event(name))
    eventCount = eventCount + 1
  end
end

-- SetEventHandler("ACCOUNT_ATTENDANCE_LOADED")
-- SetEventHandler("ACCOUNT_ATTRIBUTE_UPDATED")
-- SetEventHandler("ACCOUNT_RESTRICT_NOTICE")
-- SetEventHandler("ACTABILITY_EXPERT_EXPANDED")
-- SetEventHandler("ACTABILITY_REFRESH_ALL")
-- SetEventHandler("ACTION_BAR_AUTO_REGISTERED")
-- SetEventHandler("ACTIONS_UPDATE")
-- SetEventHandler("AGGRO_METER_CLEARED")
-- SetEventHandler("AGGRO_METER_UPDATED")
-- SetEventHandler("ALL_SIEGE_RAID_TEAM_INFOS")
-- SetEventHandler("ANTIBOT_PUNISH")
-- SetEventHandler("APPELLATION_GAINED")
-- SetEventHandler("ASK_BUY_LABOR_POWER_POTION")
-- SetEventHandler("AUCTION_BIDDED")
-- SetEventHandler("AUCTION_BIDDEN")
-- SetEventHandler("AUCTION_CHARACTER_LEVEL_TOO_LOW")
-- SetEventHandler("AUCTION_TOGGLE")
-- SetEventHandler("BAD_USER_LIST_UPDATE")
-- SetEventHandler("BADWORD_USER_REPORED_RESPONE_MSG")
-- SetEventHandler("BAG_EXPANDED")
-- SetEventHandler("BAG_ITEM_CONFIRMED")
-- SetEventHandler("BAG_REAL_INDEX_SHOW")
-- SetEventHandler("BAN_PLAYER_RESULT")
-- SetEventHandler("BANK_EXPANDED")
-- SetEventHandler("BANK_REAL_INDEX_SHOW")
-- SetEventHandler("BEAUTYSHOP_CLOSE_BY_SYSTEM")
-- SetEventHandler("BLESS_UTHSTIN_EXTEND_MAX_STATS")
-- SetEventHandler("BLESS_UTHSTIN_ITEM_SLOT_CLEAR")
-- SetEventHandler("BLESS_UTHSTIN_ITEM_SLOT_SET")
-- SetEventHandler("BLESS_UTHSTIN_MESSAGE")
-- SetEventHandler("BLESS_UTHSTIN_UPDATE_STATS")
-- SetEventHandler("BLESS_UTHSTIN_WILL_APPLY_STATS")
-- SetEventHandler("BLOCKED_USERS_INFO")
-- SetEventHandler("BOT_SUSPECT_REPORTED")
-- SetEventHandler("BUFF_SKILL_CHANGED")
-- SetEventHandler("BUILD_CONDITION")
-- SetEventHandler("BUILDER_END")
-- SetEventHandler("BUILDER_STEP")
-- SetEventHandler("BUTLER_UI_COMMAND")
-- SetEventHandler("BUY_RESULT_AA_POINT")
-- SetEventHandler("BUY_SPECIALTY_CONTENT_INFO")
-- SetEventHandler("CANDIDATE_LIST_CHANGED")
-- SetEventHandler("CANDIDATE_LIST_HIDE")
-- SetEventHandler("CANDIDATE_LIST_SELECTION_CHANGED")
-- SetEventHandler("CANDIDATE_LIST_SHOW")
-- SetEventHandler("CHANGE_ACTABILITY_DECO_NUM")
-- SetEventHandler("CHANGE_OPTION")
-- SetEventHandler("CHANGE_PAY_INFO")
-- SetEventHandler("CHANGE_VISUAL_RACE_ENDED")
-- SetEventHandler("CHANGED_AUTO_USE_AAPOINT")
-- SetEventHandler("CHANGED_MSG")
-- SetEventHandler("CHAT_DICE_VALUE")
-- SetEventHandler("CHAT_FAILED")
-- SetEventHandler("CHAT_MSG_ALARM")
-- SetEventHandler("CHAT_MSG_DOODAD")
-- SetEventHandler("CHAT_MSG_QUEST")
-- SetEventHandler("CHECK_TEXTURE")
-- SetEventHandler("CLEAR_BOSS_TELESCOPE_INFO")
-- SetEventHandler("CLEAR_CARRYING_BACKPACK_SLAVE_INFO")
-- SetEventHandler("CLEAR_COMPLETED_QUEST_INFO")
-- SetEventHandler("CLEAR_FISH_SCHOOL_INFO")
-- SetEventHandler("CLEAR_GIVEN_QUEST_STATIC_INFO")
-- SetEventHandler("CLEAR_HOUSING_INFO")
-- SetEventHandler("CLEAR_NOTIFY_QUEST_INFO")
-- SetEventHandler("CLEAR_NPC_INFO")
-- SetEventHandler("CLOSE_CRAFT_ORDER")
-- SetEventHandler("CLOSE_MUSIC_SHEET")
-- SetEventHandler("COFFER_INTERACTION_END")
-- SetEventHandler("COFFER_INTERACTION_START")
-- SetEventHandler("COFFER_REAL_INDEX_SHOW")
-- SetEventHandler("COMBAT_TEXT")
-- SetEventHandler("COMBAT_TEXT_COLLISION")
-- SetEventHandler("COMBAT_TEXT_SYNERGY")
-- SetEventHandler("COMMON_FARM_UPDATED")
-- SetEventHandler("COMMUNITY_ERROR")
-- SetEventHandler("COMPLETE_CRAFT_ORDER")
-- SetEventHandler("COMPLETE_QUEST_CONTEXT_DOODAD")
-- SetEventHandler("COMPLETE_QUEST_CONTEXT_NPC")
-- SetEventHandler("CONSOLE_WRITE")
-- SetEventHandler("COPY_RAID_MEMBERS_TO_CLIPBOARD")
-- SetEventHandler("CRAFT_DOODAD_INFO")
-- SetEventHandler("CRAFT_FAILED")
-- SetEventHandler("CRAFT_RECIPE_ADDED")
-- SetEventHandler("CRAFT_TRAINED")
-- SetEventHandler("CRAFTING_END")
-- SetEventHandler("CREATE_CHARACTER_FAILED")
-- SetEventHandler("CREATE_ORIGIN_UCC_ITEM")
-- SetEventHandler("CRIME_REPORTED")
-- SetEventHandler("DESTROY_PAPER")
-- SetEventHandler("DIAGONAL_LINE")
-- SetEventHandler("DISCONNECT_FROM_AUTH")
-- SetEventHandler("DOMINION_GUARD_TOWER_STATE_NOTICE")
-- SetEventHandler("DOMINION_GUARD_TOWER_UPDATE_TOOLTIP")
-- SetEventHandler("DOMINION_SIEGE_PARTICIPANT_COUNT_CHANGED")
-- SetEventHandler("DOMINION_SIEGE_SYSTEM_NOTICE")
-- SetEventHandler("DOODAD_LOGIC")
-- SetEventHandler("ENABLE_TEAM_AREA_INVITATION")
-- SetEventHandler("ENCHANT_EXAMINE")
-- SetEventHandler("ENCHANT_RESULT")
-- SetEventHandler("ENCHANT_SAY_ABILITY")
-- SetEventHandler("END_HERO_ELECTION_PERIOD")
-- SetEventHandler("END_QUEST_CHAT_BUBBLE")
-- SetEventHandler("ENDED_DUEL")
-- SetEventHandler("ENTER_ITEM_LOOK_CONVERT_MODE")
-- SetEventHandler("ENTER_WORLD_CANCELLED")
-- SetEventHandler("ENTERED_LOGIN")
-- SetEventHandler("ENTERED_WORLD_SELECT")
-- SetEventHandler("ESCAPE_END")
-- SetEventHandler("ESCAPE_START")
-- SetEventHandler("EVENT_SCHEDULE_START")
-- SetEventHandler("EVENT_SCHEDULE_STOP")
-- SetEventHandler("EXPEDITION_BUFF_CHANGE")
-- SetEventHandler("EXPEDITION_WAR_STATE")
-- SetEventHandler("FACTION_COMPETITION_INFO")
-- SetEventHandler("FACTION_COMPETITION_RESULT")
-- SetEventHandler("FACTION_COMPETITION_UPDATE_POINT")
-- SetEventHandler("FACTION_RELATION_ACCEPTED")
-- SetEventHandler("FACTION_RELATION_CHANGED")
-- SetEventHandler("FACTION_RELATION_COUNT")
-- SetEventHandler("GACHA_LOOT_PACK_LOG")
-- SetEventHandler("GACHA_LOOT_PACK_RESULT")
-- SetEventHandler("GAME_EVENT_EMPTY")
-- SetEventHandler("GAME_EVENT_INFO_LIST_UPDATED")
-- SetEventHandler("GAME_EVENT_INFO_REQUESTED")
-- SetEventHandler("GAME_SCHEDULE")
-- SetEventHandler("GUILD_BANK_INTERACTION_END")
-- SetEventHandler("GUILD_BANK_INTERACTION_START")
-- SetEventHandler("GUILD_BANK_MONEY_UPDATE")
-- SetEventHandler("GUILD_BANK_REAL_INDEX_SHOW")
-- SetEventHandler("GUILD_BANK_UPDATE")
-- SetEventHandler("HEIR_SKILL_ACTIVE_TYPE_MSG")
-- SetEventHandler("HERO_NOTI")
-- SetEventHandler("HOUSE_BUY_SUCCESS")
-- SetEventHandler("HOUSE_CANCEL_SELL_FAIL")
-- SetEventHandler("HOUSE_CANCEL_SELL_SUCCESS")
-- SetEventHandler("HOUSE_DECO_UPDATED")
-- SetEventHandler("HOUSE_FARM_MSG")
-- SetEventHandler("HOUSE_INFO_UPDATED")
-- SetEventHandler("HOUSE_REBUILD_TAX_INFO")
-- SetEventHandler("HOUSE_ROTATE_CONFIRM")
-- SetEventHandler("HOUSE_SALE_SUCCESS")
-- SetEventHandler("HOUSE_SET_SELL_FAIL")
-- SetEventHandler("HOUSE_SET_SELL_SUCCESS")
-- SetEventHandler("HOUSE_STEP_INFO_UPDATED")
-- SetEventHandler("ITEM_CHANGE_MAPPING_RESULT")
-- SetEventHandler("ITEM_ENCHANT_MAGICAL_RESULT")
-- SetEventHandler("ITEM_LOOK_CONVERTED")
-- SetEventHandler("ITEM_LOOK_CONVERTED_EFFECT")
-- SetEventHandler("ITEM_REFURBISHMENT_RESULT")
-- SetEventHandler("ITEM_SMELTING_RESULT")
-- SetEventHandler("ITEM_SOCKET_UPGRADE")
-- SetEventHandler("ITEM_SOCKETING_RESULT")
-- SetEventHandler("LEAVED_INSTANT_GAME_ZONE")
-- SetEventHandler("LEFT_LOGIN")
-- SetEventHandler("LEVEL_CHANGED")
-- SetEventHandler("LOGIN_CHARACTER_UPDATED")
-- SetEventHandler("OPEN_CRAFT_ORDER_BOARD")
-- SetEventHandler("OPEN_EMBLEM_IMPRINT_UI")
-- SetEventHandler("OPEN_EMBLEM_UPLOAD_UI")
-- SetEventHandler("OPEN_EXPEDITION_PORTAL_LIST")
-- SetEventHandler("OPEN_MUSIC_SHEET")
-- SetEventHandler("OPEN_WORLD_QUEUE")
-- SetEventHandler("OPTIMIZATION_RESULT_MESSAGE")
-- SetEventHandler("OPTION_RESET")
-- SetEventHandler("PLAYER_AA_POINT")
-- SetEventHandler("PLAYER_ABILITY_LEVEL_CHANGED")
-- SetEventHandler("PLAYER_BANK_AA_POINT")
-- SetEventHandler("PLAYER_GEAR_POINT")
-- SetEventHandler("SIEGE_APPOINT_RESULT")
-- SetEventHandler("SIEGE_RAID_REGISTER_LIST")
-- SetEventHandler("SIEGE_WAR_ENDED")
-- SetEventHandler("SLAVE_SHIP_BOARDING")
-- SetEventHandler("SLAVE_SHIP_UNBOARDING")
-- SetEventHandler("STARTED_DUEL")
-- SetEventHandler("STILL_LOADING")
SetEventHandler("TEAM_JOINT_BREAK")
-- SetEventHandler("TOGGLE_COMMUNITY")
-- SetEventHandler("TOGGLE_CRAFT")
-- SetEventHandler("TOGGLE_FACTION")
-- SetEventHandler("TOGGLE_IN_GAME_NOTICE")
-- SetEventHandler("TOGGLE_MEGAPHONE_CHAT")
-- SetEventHandler("TOGGLE_PET_MANAGE")
SetEventHandler("TRIAL_CANCELED")
SetEventHandler("TRIAL_MESSAGE")
-- SetEventHandler("UPDATE_BINDINGS")
-- SetEventHandler("UPDATE_CHRONICLE_INFO")
-- SetEventHandler("UPDATE_CHRONICLE_NOTIFIER")
-- SetEventHandler("UPDATE_CLIENT_DRIVEN_INFO")
SetEventHandler("UPDATE_ROSTER_MEMBER_INFO")
SetEventHandler("UPDATE_ROUTE_MAP")
-- SetEventHandler("UPDATE_SHORTCUT_SKILLS")
SetEventHandler("UPDATE_SKILL_ACTIVE_TYPE")
-- SetEventHandler("UPDATE_SLAVE_EQUIPMENT_SLOT")
SetEventHandler("UPDATE_SPECIALTY_RATIO")
-- SetEventHandler("UPDATE_ZONE_PERMISSION")
-- SetEventHandler("VIEW_CASH_BUY_WINDOW")
-- SetEventHandler("WEB_BROWSER_ESC_EVENT")
-- SetEventHandler("ZONE_SCORE_CONTENT_STATE")
-- SetEventHandler("ZONE_SCORE_UPDATED")
-- SetEventHandler("UPDATE_CONTENT_ROSTER_WINDOW")
SetEventHandler("UPDATE_MONITOR_NPC")
SetEventHandler("UPDATE_HOUSING_TOOLTIP")
SetEventHandler("UPDATE_DOMINION_INFO")
SetEventHandler("UPDATE_EXPEDITION_PORTAL")
-- SetEventHandler("MOVIE_ABORT")
-- SetEventHandler("MOVIE_LOAD")
-- SetEventHandler("MOVIE_START")
-- SetEventHandler("MOVIE_STOP")
-- SetEventHandler("MOUNT_BAG_UPDATE")
-- SetEventHandler("MOUNT_SLOT_CHANGED")
-- SetEventHandler("MOUSE_CLICK")
-- SetEventHandler("MOUSE_DOWN")
-- SetEventHandler("MOUSE_UP")
SetEventHandler("HERO_CANDIDATE_NOTI")
SetEventHandler("HERO_CANDIDATES_ANNOUNCED")
SetEventHandler("HERO_ELECTION")
SetEventHandler("HERO_ELECTION_DAY_ALERT")
SetEventHandler("HERO_ELECTION_RESULT")
SetEventHandler("HERO_ELECTION_VOTED")
SetEventHandler("HERO_RANK_DATA_TIMEOUT")
SetEventHandler("HERO_SEASON_OFF")
SetEventHandler("HERO_SEASON_UPDATED")
SetEventHandler("EXPEDITION_APPLICANT_ACCEPT")
SetEventHandler("EXPEDITION_APPLICANT_REJECT")
SetEventHandler("EXPEDITION_LEVEL_UP")
SetEventHandler("EXPEDITION_MANAGEMENT_APPLICANT_ACCEPT")
SetEventHandler("EXPEDITION_MANAGEMENT_APPLICANT_ADD")
SetEventHandler("EXPEDITION_MANAGEMENT_APPLICANT_DEL")
SetEventHandler("EXPEDITION_MANAGEMENT_APPLICANT_REJECT")
SetEventHandler("EXPEDITION_MANAGEMENT_APPLICANTS")
SetEventHandler("EXPEDITION_MANAGEMENT_GUILD_FUNCTION_CHANGED")
SetEventHandler("EXPEDITION_MANAGEMENT_MEMBER_NAME_CHANGED")
-- SetEventHandler("EXPEDITION_MANAGEMENT_MEMBER_STATUS_CHANGED")
SetEventHandler("EXPEDITION_MANAGEMENT_POLICY_CHANGED")
SetEventHandler("EXPEDITION_MANAGEMENT_RECRUITMENT_ADD")
SetEventHandler("EXPEDITION_MANAGEMENT_RECRUITMENT_DEL")
SetEventHandler("EXPEDITION_MANAGEMENT_ROLE_CHANGED")
SetEventHandler("EXPEDITION_RANKING")
SetEventHandler("EXPEDITION_SUMMON_SUGGEST")
SetEventHandler("EXPEDITION_WAR_DECLARATION_FAILED")
SetEventHandler("EXPEDITION_WAR_DECLARATION_MONEY")
SetEventHandler("FACTION_CHANGED")
SetEventHandler("FACTION_RELATION_DENIED")
SetEventHandler("FACTION_RELATION_HISTORY")
SetEventHandler("FACTION_RELATION_REQUESTED")
SetEventHandler("FACTION_RELATION_WILL_CHANGE")
SetEventHandler("FADE_INOUT_DONE")
SetEventHandler("FAIL_WEB_PLAY_DIARY_INSTANT")
SetEventHandler("FAILED_TO_SET_PET_AUTO_SKILL")
-- SetEventHandler("FAMILY_ERROR")
-- SetEventHandler("FAMILY_EXP_ADD")
-- SetEventHandler("FAMILY_INFO_REFRESH")
-- SetEventHandler("FAMILY_LEVEL_UP")
-- SetEventHandler("FAMILY_MEMBER")
-- SetEventHandler("FAMILY_MEMBER_ADDED")
-- SetEventHandler("FAMILY_MEMBER_KICKED")
-- SetEventHandler("FAMILY_MEMBER_LEFT")
-- SetEventHandler("FAMILY_MEMBER_ONLINE")
-- SetEventHandler("FAMILY_MGR")
-- SetEventHandler("FAMILY_NAME_CHANGED")
-- SetEventHandler("FAMILY_OWNER_CHANGED")
-- SetEventHandler("FAMILY_REFRESH")
-- SetEventHandler("FAMILY_REMOVED")
SetEventHandler("FIND_FACTION_REZ_DISTRICT_COOLTIME_FAIL")
SetEventHandler("FIND_FACTION_REZ_DISTRICT_DURATION_FAIL")
-- SetEventHandler("GENDER_TRANSFERED")
SetEventHandler("GOODS_MAIL_INBOX_ITEM_TAKEN")
SetEventHandler("GOODS_MAIL_INBOX_MONEY_TAKEN")
SetEventHandler("GOODS_MAIL_INBOX_TAX_PAID")
SetEventHandler("GOODS_MAIL_RETURNED")
SetEventHandler("GOODS_MAIL_SENT_SUCCESS")
SetEventHandler("GOODS_MAIL_SENTBOX_UPDATE")
SetEventHandler("GOODS_MAIL_WRITE_ITEM_UPDATE")
SetEventHandler("HOUSE_BUILD_INFO")
SetEventHandler("HOUSE_BUY_FAIL")
SetEventHandler("HOUSING_UCC_CLOSE")
SetEventHandler("HOUSING_UCC_ITEM_SLOT_CLEAR")
SetEventHandler("HOUSING_UCC_ITEM_SLOT_SET")
SetEventHandler("HOUSING_UCC_LEAVE")
SetEventHandler("HOUSING_UCC_UPDATED")
SetEventHandler("IME_STATUS_CHANGED")
SetEventHandler("INDUN_INITAL_ROUND_INFO")
SetEventHandler("INDUN_ROUND_END")
SetEventHandler("INDUN_ROUND_START")
SetEventHandler("INDUN_UPDATE_ROUND_INFO")
-- SetEventHandler("INIT_CHRONICLE_INFO")
SetEventHandler("INSTANT_GAME_BEST_RATING_REWARD")
SetEventHandler("INSTANT_GAME_END")
SetEventHandler("INSTANT_GAME_JOIN_APPLY")
SetEventHandler("INSTANT_GAME_PICK_BUFFS")
SetEventHandler("INSTANT_GAME_RETIRE")
SetEventHandler("INSTANT_GAME_ROUND_RESULT")
SetEventHandler("INSTANT_GAME_START_POINT_RETURN_MSG")
SetEventHandler("INSTANT_GAME_UNEARNED_WIN_REMAIN_TIME")
SetEventHandler("INSTANT_GAME_VISIT_COUNT_RESET")
SetEventHandler("INSTANT_GAME_WAIT")
SetEventHandler("INTERACTION_START")
SetEventHandler("INVALID_NAME_POLICY")
SetEventHandler("MAIL_RETURNED")
-- SetEventHandler("MAP_EVENT_CHANGED")
-- SetEventHandler("MATE_STATE_UPDATE")
SetEventHandler("MEGAPHONE_MESSAGE")
-- SetEventHandler("MIA_MAIL_INBOX_ITEM_TAKEN")
-- SetEventHandler("MIA_MAIL_INBOX_MONEY_TAKEN")
-- SetEventHandler("MIA_MAIL_INBOX_TAX_PAID")
-- SetEventHandler("MIA_MAIL_INBOX_UPDATE")
-- SetEventHandler("MIA_MAIL_RETURNED")
-- SetEventHandler("MIA_MAIL_SENT_SUCCESS")
-- SetEventHandler("MIA_MAIL_SENTBOX_UPDATE")
-- SetEventHandler("MIA_MAIL_WRITE_ITEM_UPDATE")
-- SetEventHandler("MINE_AMOUNT")
-- SetEventHandler("MINI_SCOREBOARD_CHANGED")
SetEventHandler("MONEY_ACQUISITION_BY_LOOT")
SetEventHandler("NAVI_MARK_POS_TO_MAP")
SetEventHandler("NAVI_MARK_REMOVE")
SetEventHandler("NEW_SKILL_POINT")
SetEventHandler("NOTIFY_AUTH_ADVERTISING_MESSAGE")
SetEventHandler("NOTIFY_AUTH_BILLING_MESSAGE")
SetEventHandler("NOTIFY_AUTH_DISCONNECTION_MESSAGE")
SetEventHandler("QUEST_CHAT_LET_IT_DONE")
SetEventHandler("QUEST_CHAT_RESTART")
SetEventHandler("QUEST_DIRECTING_MODE_END")
SetEventHandler("QUEST_ERROR_INFO")
SetEventHandler("QUEST_HIDDEN_COMPLETE")
SetEventHandler("QUEST_HIDDEN_READY")
SetEventHandler("QUEST_MSG")
SetEventHandler("QUEST_NOTIFIER_START")
SetEventHandler("QUEST_QUICK_CLOSE_EVENT")
SetEventHandler("RANDOM_SHOP_UPDATE")
SetEventHandler("RANK_ALARM_MSG")
SetEventHandler("RANK_DATA_RECEIVED")
SetEventHandler("RANK_LOCK")
SetEventHandler("RANK_REWARD_SNAPSHOTS")
SetEventHandler("RANK_SEASON_RESULT_RECEIVED")
SetEventHandler("RANK_UNLOCK")
SetEventHandler("READY_TO_CONNECT_WORLD")
SetEventHandler("RECOVERABLE_EXP")
SetEventHandler("RECOVERED_EXP")
SetEventHandler("REMOVE_BOSS_TELESCOPE_INFO")
SetEventHandler("REMOVE_CARRYING_BACKPACK_SLAVE_INFO")
SetEventHandler("REMOVE_FISH_SCHOOL_INFO")
SetEventHandler("REMOVE_PING")
SetEventHandler("REMOVE_TRANSFER_TELESCOPE_INFO")
SetEventHandler("RENEW_ITEM_SUCCEEDED")
SetEventHandler("REPORT_CRIME")
SetEventHandler("REPUTATION_GIVEN")
SetEventHandler("REQUIRE_DELAY_TO_CHAT")
SetEventHandler("REQUIRE_ITEM_TO_CHAT")
SetEventHandler("RESET_INGAME_SHOP_MODELVIEW")
SetEventHandler("RESIDENT_SERVICE_POINT_CHANGED")
SetEventHandler("SELECTED_INSTANCE_DIFFICULT")
SetEventHandler("SELL_SPECIALTY")
SetEventHandler("SHOW_ADD_TAB_WINDOW")
SetEventHandler("SHOW_CHARACTER_ABILITY_WINDOW")
SetEventHandler("SHOW_CHARACTER_CREATE_WINDOW")
SetEventHandler("SHOW_CHARACTER_CUSTOMIZE_WINDOW")
SetEventHandler("SHOW_CHARACTER_SELECT_WINDOW")
SetEventHandler("SHOW_SERVER_SELECT_WINDOW")
SetEventHandler("SIM_DOODAD_MSG")
SetEventHandler("SKILL_CHANGED")
SetEventHandler("SKILL_DEBUG_MSG")
SetEventHandler("SKILL_SELECTIVE_ITEM_NOT_AVAILABLE")
SetEventHandler("SKILL_UPGRADED")
SetEventHandler("SPECIAL_ABILITY_LEARNED")
SetEventHandler("SPECIALTY_CONTENT_RECIPE_INFO")
SetEventHandler("SPECIALTY_RATIO_BETWEEN_INFO")
SetEventHandler("START_QUEST_CONTEXT")
SetEventHandler("START_CHAT_BUBBLE")
SetEventHandler("START_QUEST_CONTEXT_DOODAD")
SetEventHandler("START_QUEST_CONTEXT_NPC")
SetEventHandler("START_QUEST_CONTEXT_SPHERE")
SetEventHandler("TEAM_JOINT_CHAT")
SetEventHandler("TEAM_JOINT_RESPONSE")
SetEventHandler("TEAM_JOINT_TARGET")
SetEventHandler("TEAM_SUMMON_SUGGEST")
SetEventHandler("TRADE_CAN_START")
SetEventHandler("TRADE_CANCELED")
SetEventHandler("TRADE_ITEM_TOOKDOWN")
SetEventHandler("TRADE_ITEM_UPDATED")
SetEventHandler("TRADE_OTHER_ITEM_PUTUP")
SetEventHandler("TRADE_OTHER_ITEM_TOOKDOWN")
SetEventHandler("TRADE_OTHER_MONEY_PUTUP")
SetEventHandler("TRADE_UI_TOGGLE")
SetEventHandler("TRADE_UNLOCKED")
SetEventHandler("STORE_ADD_BUY_ITEM")
SetEventHandler("STORE_FULL")
SetEventHandler("STORE_TRADE_FAILED")
SetEventHandler("EQUIP_SLOT_REINFORCE_MSG_SET_EFFECT")
SetEventHandler("REPRESENT_CHARACTER_RESULT")
SetEventHandler("LP_MANAGE_CHARACTER_CHANGED")
SetEventHandler("ROLLBACK_FAVORITE_CRAFTS")
SetEventHandler("NATION_DOMINION")
SetEventHandler("SECOND_PASSWORD_ACCOUNT_LOCKED")
SetEventHandler("SECOND_PASSWORD_CHANGE_COMPLETED")
SetEventHandler("SECOND_PASSWORD_CHECK_COMPLETED")
SetEventHandler("SECOND_PASSWORD_CHECK_OVER_FAILED")
SetEventHandler("SECOND_PASSWORD_CLEAR_COMPLETED")
SetEventHandler("SECOND_PASSWORD_CREATION_COMPLETED")
SetEventHandler("UPDATE_NPC_INFO_BROADCASTING")
SetEventHandler("UPDATE_FISH_SCHOOL_AREA")
SetEventHandler("UPDATE_FISH_SCHOOL_INFO")
SetEventHandler("UPDATE_GIVEN_QUEST_STATIC_INFO")
SetEventHandler("UPDATE_HERO_ELECTION_CONDITION")
SetEventHandler("UPDATE_INGAME_BEAUTYSHOP_STATUS")
SetEventHandler("UPDATE_INSTANT_GAME_KILLSTREAK")
-- SetEventHandler("UPDATE_COMPLETED_QUEST_INFO")
SetEventHandler("UPDATE_DEFENCE_INFO")
SetEventHandler("UPDATE_DYEING_EXCUTABLE")
SetEventHandler("UPDATE_RETURN_ACCOUNT_STATUS")
SetEventHandler("UPDATE_CARRYING_BACKPACK_SLAVE_INFO")
SetEventHandler("UPDATE_CHANGE_VISUAL_RACE_WND")
SetEventHandler("UPDATE_BOSS_TELESCOPE_AREA")
SetEventHandler("UPDATE_BOSS_TELESCOPE_INFO")
SetEventHandler("UPDATE_BOT_CHECK_INFO")
SetEventHandler("UNIT_NPC_EQUIPMENT_CHANGED")
SetEventHandler("UCC_IMPRINT_SUCCEEDED")
SetEventHandler("UI_RELOADED")
-- SetEventHandler("ULC_ACTIVATE")
-- SetEventHandler("ULC_SKILL_MSG")
SetEventHandler("UNFINISHED_BUILD_HOUSE")
-- SetEventHandler("TUTORIAL_EVENT")
SetEventHandler("SURVEY_FORM_UPDATE")
SetEventHandler("SYNC_PORTAL")
SetEventHandler("SYS_INDUN_STAT_UPDATED")
-- SetEventHandler("TENCENT_HEALTH_CARE_URL")
SetEventHandler("TIME_MESSAGE")
SetEventHandler("TOGGLE_CHANGE_VISUAL_RACE")
-- SetEventHandler("TRANSFORM_COMBAT_RESOURCE")
-- SetEventHandler("LOGIN_DENIED")
-- SetEventHandler("NOTIFY_AUTH_FATIGUE_MESSAGE")
-- SetEventHandler("NOTIFY_AUTH_NOTICE_MESSAGE")
-- SetEventHandler("NOTIFY_AUTH_TC_FATIGUE_MESSAGE")
-- SetEventHandler("NOTIFY_WEB_TRANSFER_STATE")
-- SetEventHandler("NPC_CRAFT_ERROR")
-- SetEventHandler("NPC_CRAFT_UPDATE")
-- SetEventHandler("NPC_INTERACTION_END")
-- SetEventHandler("NPC_INTERACTION_START")
SetEventHandler("NUONS_ARROW_SHOW")
SetEventHandler("NUONS_ARROW_UI_MSG")
SetEventHandler("NUONS_ARROW_UPDATE")
-- SetEventHandler("ONE_AND_ONE_CHAT_ADD_MESSAGE")
-- SetEventHandler("ONE_AND_ONE_CHAT_END")
-- SetEventHandler("ONE_AND_ONE_CHAT_START")
-- SetEventHandler("OPEN_ARS")
-- SetEventHandler("OPEN_COMMON_FARM_INFO")
-- SetEventHandler("OPEN_NAVI_DOODAD_NAMING_DIALOG")
-- SetEventHandler("OPEN_OTP")
-- SetEventHandler("OPEN_PAPER")
-- SetEventHandler("OPEN_PCCERT")
-- SetEventHandler("OPEN_PROMOTION_EVENT_URL")
-- SetEventHandler("OPEN_SECURE_CARD")
-- SetEventHandler("PLAYER_VISUAL_RACE")
SetEventHandler("PREMIUM_FIRST_BUY_BONUS")
SetEventHandler("PREMIUM_GRADE_CHANGE")
SetEventHandler("PREMIUM_LABORPOWER_CHANGED")
SetEventHandler("PREMIUM_POINT_CHANGE")
SetEventHandler("PREMIUM_SERVICE_BUY_RESULT")
SetEventHandler("PREMIUM_SERVICE_LIST_UPDATED")
SetEventHandler("PROCESS_CRAFT_ORDER")
SetEventHandler("PROGRESS_TALK_QUEST_CONTEXT")
SetEventHandler("REENTRY_NOTIFY_DISABLE")
SetEventHandler("REENTRY_NOTIFY_ENABLE")
-- SetEventHandler("REFRESH_WORLD_QUEUE")
SetEventHandler("RELOAD_CASH")
SetEventHandler("RENAME_CHARACTER_FAILED")
SetEventHandler("SELL_SPECIALTY_CONTENT_INFO")
-- SetEventHandler("SENSITIVE_OPERATION_VERIFY")
-- SetEventHandler("SENSITIVE_OPERATION_VERIFY_SUCCESS")
-- SetEventHandler("SET_EFFECT_ICON_VISIBLE")
-- SetEventHandler("SET_LOGIN_BROWSER_URL")
-- SetEventHandler("SET_UI_MESSAGE")
-- SetEventHandler("SET_WEB_MESSENGE_COUNT")
-- SetEventHandler("SHOW_GAME_RATING")
-- SetEventHandler("SHOW_HEALTH_NOTICE")
-- SetEventHandler("SHOW_HIDDEN_BUFF")
-- SetEventHandler("SHOW_LOGIN_WINDOW")
-- SetEventHandler("SHOW_PRIVACY_POLICY_WINDOW")
-- SetEventHandler("SHOW_RAID_FRAME_SETTINGS")
-- SetEventHandler("SHOW_RECOMMEND_USING_SECOND_PASSWORD")
-- SetEventHandler("SHOW_RENAME_EXPEIDITON")
SetEventHandler("START_HERO_ELECTION_PERIOD")
SetEventHandler("STICKED_MSG")
SetEventHandler("START_TALK_QUEST_CONTEXT")
SetEventHandler("HOTKEY_ACTION")
-- SetEventHandler("RAID_RECRUIT_DETAIL")
-- SetEventHandler("RAID_RECRUIT_HUD")
-- SetEventHandler("RAID_RECRUIT_LIST")

-- SetEventHandler("START_SENSITIVE_OPERATION")

-- SetEventHandler("STARTING_QUEST_COMPLETED") -- crash
-- SetEventHandler("TARGET_NPC_HEALTH_CHANGED_FOR_DEFENCE_INFO") -- crash?
-- SetEventHandler("TARGET_NPC_HEALTH_CHANGED_FOR_VERSUS_FACTION") -- crash?
-- SetEventHandler("EQUIP_SLOT_REINFORCE_MSG_CHANGE_LEVEL_EFFECT") -- crash
-- SetEventHandler("HOUSE_TAX_INFO")
-- SetEventHandler("REPORT_BAD_USER_UPDATE") -- crash?
-- SetEventHandler("SHOW_DEFENDANT_WAIT_JURY") --crash?
-- SetEventHandler("SHOW_DEFENDANT_WAIT_TRIAL") --crash?
-- SetEventHandler("UPDATE_BUBBLE") -- crash
-- SetEventHandler("NPC_UNIT_EQUIPMENT_CHANGED") -- crash


-- -----------------------------------------------------------------------------

---Dumps a table line by line to the chat.
---@param var table
---@param ctx? ctx
function ADDON:ChatLogTable(var, ctx)
  local output = dump(var, ctx)
  for line in output:gmatch("([^\n]*)\n?") do
    ADDON:ChatLog(line)
  end
end

-- ADDON:ChatLogTable(_G)--, { indent_type = ">" })

-- ADDON:ChatLog(UIParent:GetCharacterTodayPlayedTimeStamp())
-- ADDON:ImportAPI(API.X2Auction)
-- ADDON:ChatLog(tostring(X2Auction:GetLowestPrice(8343, 1)))
-- ADDON:ImportAPI(API.X2Bag)
-- ADDON:ChatLogTable(X2Bag:GetBagItemInfo(0, 1))

ADDON:ImportAPI(API.X2Unit)
ADDON:ImportAPI(API.X2Ability)

-- ADDON:ChatLog("BIK_RUNTIME_TIMELEFT")
-- ADDON:ChatLogTable(X2Unit:UnitHiddenBuffTooltip("player", 2, BIK_DESCRIPTION))
-- ADDON:ChatLogTable(X2Unit:UnitRemovableDebuffCount("player"))
-- ADDON:ChatLog(string.rep("=", 4))

-- ADDON:ChatLog("BIK_RUNTIME_TIMELEFT")
-- ADDON:ChatLogTable(X2Ability:GetBuffTooltip(5700, 1, BIK_RUNTIME_TIMELEFT))
-- ADDON:ChatLog(string.rep("=", 4))

-- ADDON:ChatLog("BIK_DESCRIPTION")
-- ADDON:ChatLogTable(X2Ability:GetBuffTooltip(5700, 1, BIK_DESCRIPTION))
-- ADDON:ChatLog(string.rep("=", 4))

-- ADDON:ChatLog("BIK_RUNTIME_ALL")
-- ADDON:ChatLogTable(X2Ability:GetBuffTooltip(5700, 1, BIK_RUNTIME_ALL))
-- ADDON:ChatLog(string.rep("=", 4))

-- ADDON:ChatLog("BIK_RUNTIME_DURATION")
-- ADDON:ChatLogTable(X2Ability:GetBuffTooltip(5700, 1, BIK_RUNTIME_DURATION))
-- ADDON:ChatLog(string.rep("=", 4))

-- ADDON:ChatLog("BIK_RUNTIME_MINE")
-- ADDON:ChatLogTable(X2Ability:GetBuffTooltip(5700, 1, BIK_RUNTIME_MINE))
-- ADDON:ChatLog(string.rep("=", 4))

-- ADDON:ChatLog("BIK_RUNTIME_STACK")
-- ADDON:ChatLogTable(X2Ability:GetBuffTooltip(5700, 1, BIK_RUNTIME_STACK))
-- ADDON:ChatLog(string.rep("=", 4))

-- ADDON:ChatLog("BIK_RUNTIME_STACK + BIK_DESCRIPTION")
-- ADDON:ChatLogTable(X2Ability:GetBuffTooltip(5700, 1, BIK_RUNTIME_STACK + BIK_DESCRIPTION))
-- ADDON:ChatLog(string.rep("=", 4))

-- ADDON:ChatLog("NONE")
-- ADDON:ChatLogTable(X2Ability:GetBuffTooltip(5700, 1))
-- ADDON:ChatLog(string.rep("=", 4))

-- local slot = UIParent:CreateWidget("slot", "x", "UIParent")
-- slot:SetExtent(128, 128)
-- slot:AddAnchor("CENTER", 0, 0)
-- slot:EstablishSlot(ISLOT_BAG, 1)
-- slot:EstablishSkillAlert(21, 2000, 4000)

-- ADDON:ImportAPI(API.X2Equipment)
-- slot:EstablishVirtualSlot(ISLOT_EQUIPMENT, ES_RANGED - 1, 1)
-- slot:EstablishSlot(ISLOT_EQUIPMENT, ES_ARMS)
-- slot:EstablishSlot(ISLOT_PRELIMINARY_EQUIPMENT, ES_MAINHAND)
-- slot:EstablishSlot(ISLOT_HEIR_SKILL_VIEW, 1)
-- slot:EstablishSlot(ISLOT_ABILITY_VIEW, ATTACK_SKILL + 1)
-- slot:EstablishSlot(ISLOT_ACTION, 1)
-- slot:EstablishSlot(ISLOT_BAG, 1)
-- slot:EstablishSlot(ISLOT_BANK, 1)
-- slot:EstablishSlot(ISLOT_COFFER, 1)
-- slot:EstablishSlot(ISLOT_CONSTANT, 0) -- idk?
-- slot:EstablishSlot(ISLOT_GUILD_BANK, 1) -- idk?
-- slot:EstablishSlot(ISLOT_MODE_ACTION, 1)
-- slot:EstablishSlot(ISLOT_ORIGIN_SKILL_VIEW, 1)
-- slot:EstablishSlot(ISLOT_PET_BATTLE_ACTION, 1)
-- slot:EstablishSlot(ISLOT_PET_RIDE_ACTION, 1)
-- slot:EstablishSlot(ISLOT_SHORTCUT_ACTION, 1) -- idk
-- slot:EstablishSlot(ISLOT_SKILL_ALERT, 1) -- idk

-- slot:EstablishVirtualSlot(ISLOT_PRELIMINARY_EQUIPMENT, ES_MAINHAND)
-- slot:Show(true)

-- slot:EstablishSkill(14495)

ADDON:ImportAPI(API.X2Chat)
ADDON:ImportAPI(API.X2Util)

local a = UIParent:CreateWidget("button", "a", "UIParent")

local editbox = widgetassert(UIParent:CreateWidget("megaphonechatedit", "test", "UIParent"))
editbox:SetExtent(100, 100)
editbox:AddAnchor("CENTER", 0, 0)
-- editbox:Show(true)

editbox:SetChannel(CHAT_RAID)
editbox:CheckNamePolicy(NRT_CHAT_TAB)
editbox:SetInitVal(100)

ADDON:ImportAPI(API.X2Skill)
ADDON:ImportAPI(API.X2Mate)
-- ADDON:ChatLog(tostring(X2Skill:GetMateCooldown(9000168, false, MATE_TYPE_RIDE)))
-- ADDON:ChatLog(tostring(X2Skill:GetMateCooldown(9000168, true, MATE_TYPE_RIDE)))

ADDON:ImportAPI(API.X2Hotkey)
-- X2Hotkey:SetOptionBindingButtonWithIndex("front_camera", "`", 1)
-- X2Hotkey:SetOptionBindingWithIndex("front_camera", "SHIFT-`", 1, 0)
-- X2Hotkey:SaveHotKey()


ADDON:ChatLog(tostring(eventCount))
ADDON:ChatLog(string.rep("=", 16))
