---@meta _

MAX_ACTION_BAR_COUNT = 6 -- api/X2Option
OISLT_CHARACTER = 1 -- api/X2Option
OISLT_CHARACTER_MODE = 3 -- api/X2Option
OISLT_SYSTEM = 2 -- api/X2Option
OIT_ACTION_BAR_LOCK = 104 -- api/X2Option
OIT_AUTO_ENEMY_TARGETING = 72 -- api/X2Option
OIT_AUTO_USE_ONLY_MY_PORTAL = 73 -- api/X2Option
OIT_BASIC_CURSOR_SHAPE = 89 -- api/X2Option
OIT_CAMERA_USE_SHAKE = 84 -- api/X2Option
OIT_CLICK_TO_MOVE = 64 -- api/X2Option
OIT_COMBAT_MSG_DISPLAY_SHIP_COLLISION = 79 -- api/X2Option
OIT_COMBAT_MSG_LEVEL = 77 -- api/X2Option
OIT_COMBAT_MSG_VISIBILITY = 78 -- api/X2Option
OIT_CR_INVERT_X_AXIS = 86 -- api/X2Option
OIT_CR_INVERT_Y_AXIS = 87 -- api/X2Option
OIT_CR_SENSITIVITY = 85 -- api/X2Option
OIT_CURSOR_SIZE = 88 -- api/X2Option
OIT_CUSTOM_CAMERA_MAX_DIST = 82 -- api/X2Option
OIT_CUSTOM_FOV = 81 -- api/X2Option
OIT_CUSTOM_ZOOM_SENSITIVITY = 83 -- api/X2Option
OIT_DECORATION_SMART_POSITIONING = 68 -- api/X2Option
OIT_DOODAD_SMART_POSITIONING = 67 -- api/X2Option
OIT_E_CUSTOM_CLONE_MODE = 109 -- api/X2Option
OIT_E_CUSTOM_MAX_CLONE_MODEL = 110 -- api/X2Option
OIT_E_CUSTOM_MAX_MODEL = 111 -- api/X2Option
OIT_E_ZONEWEATHEREFFECT = 28 -- api/X2Option
OIT_FIRE_ACTION_ON_BUTTON_DOWN = 71 -- api/X2Option
OIT_FIXEDTOOLTIPPOSITION = 129 -- api/X2Option
OIT_GIVEN_QUEST_DISTANCE_DISPLAY_MODE = 120 -- api/X2Option
OIT_GLIDER_START_WITH_DOUBLE_JUMP = 66 -- api/X2Option
OIT_G_HIDE_TUTORIAL = 107 -- api/X2Option
OIT_G_IGNORE_CHAT_FILTER = 103 -- api/X2Option
OIT_G_IGNORE_DUEL_INVITE = 102 -- api/X2Option
OIT_G_IGNORE_EXPEDITION_INVITE = 97 -- api/X2Option
OIT_G_IGNORE_FAMILY_INVITE = 98 -- api/X2Option
OIT_G_IGNORE_JURY_INVITE = 99 -- api/X2Option
OIT_G_IGNORE_PARTY_INVITE = 93 -- api/X2Option
OIT_G_IGNORE_RAID_INVITE = 94 -- api/X2Option
OIT_G_IGNORE_RAID_JOINT = 95 -- api/X2Option
OIT_G_IGNORE_SQUAD_INVITE = 96 -- api/X2Option
OIT_G_IGNORE_TRADE_INVITE = 100 -- api/X2Option
OIT_G_IGNORE_WHISPER_INVITE = 101 -- api/X2Option
OIT_G_SHOW_LOOT_WINDOW = 108 -- api/X2Option
OIT_G_USE_CHAT_TIME_STAMP = 118 -- api/X2Option
OIT_ITEM_MAKER_INFO_SHOW_TOOLTIP = 92 -- api/X2Option
OIT_MASTERGRAHICQUALITY = 122 -- api/X2Option
OIT_NAME_TAG_APPELLATION_SHOW = 51 -- api/X2Option
OIT_NAME_TAG_EXPEDITIONFAMILY_SHOW = 305 -- api/X2Option
OIT_NAME_TAG_EXPEDITION_SHOW = 56 -- api/X2Option
OIT_NAME_TAG_FACTION_SELECTION = 63 -- api/X2Option
OIT_NAME_TAG_FACTION_SHOW = 52 -- api/X2Option
OIT_NAME_TAG_FRIENDLY_MATE_SHOW = 60 -- api/X2Option
OIT_NAME_TAG_FRIENDLY_SHOW = 57 -- api/X2Option
OIT_NAME_TAG_HOSTILE_MATE_SHOW = 61 -- api/X2Option
OIT_NAME_TAG_HOSTILE_SHOW = 58 -- api/X2Option
OIT_NAME_TAG_HP_SHOW = 53 -- api/X2Option
OIT_NAME_TAG_MODE = 50 -- api/X2Option
OIT_NAME_TAG_MY_MATE_SHOW = 59 -- api/X2Option
OIT_NAME_TAG_NPC_SHOW = 62 -- api/X2Option
OIT_NAME_TAG_PARTY_SHOW = 55 -- api/X2Option
OIT_NAME_TAG_SELF_ENABLE = 54 -- api/X2Option
OIT_NEXT_OPTION_SOUND = 40 -- api/X2Option
OIT_NEXT_R_DRIVER = 9 -- api/X2Option
OIT_NEXT_R_MULTITHREADED = 8 -- api/X2Option
OIT_NEXT_SYS_SPEC_FULL = 11 -- api/X2Option
OIT_OPTION_ANIMATION = 39 -- api/X2Option
OIT_OPTION_ANTI_ALIASING = 35 -- api/X2Option
OIT_OPTION_CAMERA_FOV_SET = 80 -- api/X2Option
OIT_OPTION_CHARACTER_LOD = 20 -- api/X2Option
OIT_OPTION_CHARACTER_PRIVACY_STATUS = 119 -- api/X2Option
OIT_OPTION_CUSTOM_ADDON_FONTS = 311 -- api/X2Option
OIT_OPTION_CUSTOM_ADDON_UI = 312 -- api/X2Option
OIT_OPTION_CUSTOM_SKILL_QUEUE = 310 -- api/X2Option
OIT_OPTION_DISABLE_PRIVATE_MESSAGE_MUSIC = 300 -- api/X2Option
OIT_OPTION_EFFECT = 30 -- api/X2Option
OIT_OPTION_ENABLE_COMBAT_CHAT_LOG = 302 -- api/X2Option
OIT_OPTION_ENABLE_MISC_CHAT_LOG = 303 -- api/X2Option
OIT_OPTION_GAME_LOGS_LIFE_TIME = 304 -- api/X2Option
OIT_OPTION_HIDE_BLOODLUST_MODE = 309 -- api/X2Option
OIT_OPTION_HIDE_ENCHANT_BROADCAST = 306 -- api/X2Option
OIT_OPTION_HIDE_MOBILIZATION_ORDER = 308 -- api/X2Option
OIT_OPTION_ITEM_MOUNT_ONLY_MY_PET = 76 -- api/X2Option
OIT_OPTION_MAP_GIVEN_QUEST_DISTANCE = 112 -- api/X2Option
OIT_OPTION_OPTIMIZATION_ENABLE = 113 -- api/X2Option
OIT_OPTION_OVERHEAD_MARKER_FIXED_SIZE = 307 -- api/X2Option
OIT_OPTION_SHADER_QUALITY = 25 -- api/X2Option
OIT_OPTION_SHADOW_DIST = 22 -- api/X2Option
OIT_OPTION_SHADOW_VIEW_DIST_RATIO = 24 -- api/X2Option
OIT_OPTION_SHADOW_VIEW_DIST_RATIO_CHARACTER = 23 -- api/X2Option
OIT_OPTION_SHOW_COMBAT_RESOURCE_WINDOW = 117 -- api/X2Option
OIT_OPTION_SKILL_ALERT_ENABLE = 115 -- api/X2Option
OIT_OPTION_SKILL_ALERT_POSITION = 116 -- api/X2Option
OIT_OPTION_TERRAIN_DETAIL = 15 -- api/X2Option
OIT_OPTION_TERRAIN_LOD = 17 -- api/X2Option
OIT_OPTION_TEXTURE_BG = 12 -- api/X2Option
OIT_OPTION_TEXTURE_CHARACTER = 13 -- api/X2Option
OIT_OPTION_USE_CLOUD = 27 -- api/X2Option
OIT_OPTION_USE_DOF = 34 -- api/X2Option
OIT_OPTION_USE_HDR = 33 -- api/X2Option
OIT_OPTION_USE_KR_FONTS = 301 -- api/X2Option
OIT_OPTION_USE_SHADOW = 21 -- api/X2Option
OIT_OPTION_USE_WATER_REFLECTION = 32 -- api/X2Option
OIT_OPTION_VIEW_DISTANCE = 14 -- api/X2Option
OIT_OPTION_VIEW_DIST_RATIO = 18 -- api/X2Option
OIT_OPTION_VIEW_DIST_RATIO_VEGETATION = 19 -- api/X2Option
OIT_OPTION_VOLUMETRIC_EFFECT = 26 -- api/X2Option
OIT_OPTION_WATER = 31 -- api/X2Option
OIT_OPTION_WEAPON_EFFECT = 29 -- api/X2Option
OIT_R_DESIREHEIGHT = 3 -- api/X2Option
OIT_R_DESIREWIDTH = 2 -- api/X2Option
OIT_R_FULLSCREEN = 1 -- api/X2Option
OIT_R_GAMMA = 4 -- api/X2Option
OIT_R_PIXELSYNC = 10 -- api/X2Option
OIT_R_VSYNC = 7 -- api/X2Option
OIT_SHOWACTIONBAR_1 = 135 -- api/X2Option
OIT_SHOWACTIONBAR_2 = 136 -- api/X2Option
OIT_SHOWACTIONBAR_3 = 137 -- api/X2Option
OIT_SHOWACTIONBAR_4 = 138 -- api/X2Option
OIT_SHOWACTIONBAR_5 = 139 -- api/X2Option
OIT_SHOWACTIONBAR_6 = 140 -- api/X2Option
OIT_SHOWBUFFDURATION = 125 -- api/X2Option
OIT_SHOWCHATBUBBLE = 131 -- api/X2Option
OIT_SHOWEMPTYBAGSLOTCOUNTER = 130 -- api/X2Option
OIT_SHOWFPS = 132 -- api/X2Option
OIT_SHOWGAMETIME = 313 -- api/X2Option
OIT_SHOWHEATLTHNUMBER = 123 -- api/X2Option
OIT_SHOWMAGICPOINTNUMBER = 124 -- api/X2Option
OIT_SHOWPLAYERFRAMELIFEALERTEFFECT = 133 -- api/X2Option
OIT_SHOWSERVERTIME = 314 -- api/X2Option
OIT_SHOWTARGETCASTINGBAR = 126 -- api/X2Option
OIT_SHOWTARGETTOTARGETCASTINGBAR = 127 -- api/X2Option
OIT_SHOW_GUIDEDECAL = 69 -- api/X2Option
OIT_SKILL_DETAIL_DAMAGE_SHOW_TOOLTIP = 91 -- api/X2Option
OIT_SKILL_SYNERGY_INFO_SHOW_TOOLTIP = 90 -- api/X2Option
OIT_SLOT_COOLDOWN_VISIBLE = 106 -- api/X2Option
OIT_SMART_GROUND_TARGETING = 74 -- api/X2Option
OIT_SOUND_MOOD_COMBAT_ENABLE = 44 -- api/X2Option
OIT_SYS_MAX_FPS = 5 -- api/X2Option
OIT_SYS_USE_LIMIT_FPS = 6 -- api/X2Option
OIT_S_CINEMAVOLUME = 45 -- api/X2Option
OIT_S_GAMEMASTERVOLUME = 41 -- api/X2Option
OIT_S_MIDIVOLUME = 46 -- api/X2Option
OIT_S_MUSICVOLUME = 42 -- api/X2Option
OIT_S_SFXVOLUME = 43 -- api/X2Option
OIT_S_VEHCLEMUSICVOLUME = 49 -- api/X2Option
OIT_UI_SCALE = 121 -- api/X2Option
OIT_USEQUESTDIRECTINGCLOSEUPCAMERA = 134 -- api/X2Option
OIT_USER_MUSIC_DISABLE_OTHERS = 48 -- api/X2Option
OIT_USER_MUSIC_DISABLE_SELF = 47 -- api/X2Option
OIT_USE_AUTO_REGIST_DISTRICT = 75 -- api/X2Option
OIT_USE_CELERITY_WITH_DOUBLE_FORWARD = 65 -- api/X2Option
OIT_VISIBLEMYEQUIPINFO = 128 -- api/X2Option
X2Option = {} -- api/X2Option

function X2Option:CreateOptionItemFloat() end

function X2Option:CreateOptionItemString() end

function X2Option:EnumAAFormats() end

function X2Option:GetBasicCursorShape() end

function X2Option:GetConsoleVariable() end

function X2Option:GetCursorSize() end

function X2Option:GetMinxMaxOfMouseSensitivity() end

function X2Option:GetNextSysSpecFullValue() end

function X2Option:GetOptionInfo() end

function X2Option:GetOptionItemValue() end

function X2Option:GetOptionItemValueByName() end

function X2Option:GetResolution() end

function X2Option:GetResolutionCount() end

function X2Option:GetSubOptionItemList() end

function X2Option:HasOceanSimulateOption() end

function X2Option:IsPixelSyncSupported() end

function X2Option:OptimizationEnable() end

function X2Option:Reset() end

function X2Option:Save() end

function X2Option:SetConsoleVariable() end

function X2Option:SetItemDefaultFloatValue() end

function X2Option:SetItemDefaultFloatValueByName() end

function X2Option:SetItemDefaultStringValue() end

function X2Option:SetItemDefaultStringValueByName() end

function X2Option:SetItemFloatValue() end

function X2Option:SetItemFloatValueByName() end

function X2Option:SetItemFloatValueWithoutModify() end

function X2Option:SetItemStringValue() end

function X2Option:SetItemStringValueByName() end